CREATE TABLE "AA10"
(
"AAA100" VARCHAR2(20) NOT NULL,
"AAA101" VARCHAR2(50) NOT NULL,
"AAA102" VARCHAR2(6) NOT NULL,
"AAA103" VARCHAR2(50) NOT NULL,
"YAB003" VARCHAR2(6) NOT NULL,
"AAE120" VARCHAR2(6) NOT NULL,
"VER" NUMBER(10,0),
CONSTRAINT "PK_AA10" NOT CLUSTER PRIMARY KEY("AAA100", "AAA102")) STORAGE(ON "MAIN", CLUSTERBTR) ;
COMMENT ON TABLE "AA10" IS 'AA10�����';
COMMENT ON COLUMN "AA10"."AAA100" IS 'AAA100�������';
COMMENT ON COLUMN "AA10"."AAA101" IS 'AAA102����ֵ';
COMMENT ON COLUMN "AA10"."AAA102" IS 'AAA102����ֵ';
COMMENT ON COLUMN "AA10"."AAA103" IS 'AAA103��������';
COMMENT ON COLUMN "AA10"."AAE120" IS 'AAE120ע����־';
COMMENT ON COLUMN "AA10"."YAB003" IS 'YAB003�������';

CREATE TABLE "QRTZ_JOB_DETAILS"
(
"SCHED_NAME" VARCHAR2(120) NOT NULL,
"JOB_NAME" VARCHAR2(200) NOT NULL,
"JOB_GROUP" VARCHAR2(200) NOT NULL,
"DESCRIPTION" VARCHAR2(250),
"JOB_CLASS_NAME" VARCHAR2(250) NOT NULL,
"IS_DURABLE" VARCHAR2(1) NOT NULL,
"IS_NONCONCURRENT" VARCHAR2(1) NOT NULL,
"IS_UPDATE_DATA" VARCHAR2(1) NOT NULL,
"REQUESTS_RECOVERY" VARCHAR2(1) NOT NULL,
"JOB_DATA" BLOB,
CONSTRAINT "QRTZ_JOB_DETAILS_PK" NOT CLUSTER PRIMARY KEY("SCHED_NAME", "JOB_NAME", "JOB_GROUP")) STORAGE(ON "MAIN", CLUSTERBTR) ;
CREATE  INDEX "IDX_QRTZ_J_GRP" ON "QRTZ_JOB_DETAILS"("SCHED_NAME" ASC,"JOB_GROUP" ASC) STORAGE(ON "MAIN", CLUSTERBTR) ;
CREATE  INDEX "IDX_QRTZ_J_REQ_RECOVERY" ON "QRTZ_JOB_DETAILS"("SCHED_NAME" ASC,"REQUESTS_RECOVERY" ASC) STORAGE(ON "MAIN", CLUSTERBTR) ;

CREATE TABLE "QRTZ_TRIGGERS"
(
"SCHED_NAME" VARCHAR2(120) NOT NULL,
"TRIGGER_NAME" VARCHAR2(200) NOT NULL,
"TRIGGER_GROUP" VARCHAR2(200) NOT NULL,
"JOB_NAME" VARCHAR2(200) NOT NULL,
"JOB_GROUP" VARCHAR2(200) NOT NULL,
"DESCRIPTION" VARCHAR2(250),
"NEXT_FIRE_TIME" NUMBER(13,0),
"PREV_FIRE_TIME" NUMBER(13,0),
"PRIORITY" NUMBER(13,0),
"TRIGGER_STATE" VARCHAR2(16) NOT NULL,
"TRIGGER_TYPE" VARCHAR2(8) NOT NULL,
"START_TIME" NUMBER(13,0) NOT NULL,
"END_TIME" NUMBER(13,0),
"CALENDAR_NAME" VARCHAR2(200),
"MISFIRE_INSTR" NUMBER(2,0),
"JOB_DATA" BLOB,
CONSTRAINT "QRTZ_TRIGGERS_PK" NOT CLUSTER PRIMARY KEY("SCHED_NAME", "TRIGGER_NAME", "TRIGGER_GROUP"),
CONSTRAINT "QRTZ_TRIGGER_TO_JOBS_FK" FOREIGN KEY("SCHED_NAME", "JOB_NAME", "JOB_GROUP") REFERENCES "QRTZ_JOB_DETAILS"("SCHED_NAME", "JOB_NAME", "JOB_GROUP")) STORAGE(ON "MAIN", CLUSTERBTR) ;
CREATE  INDEX "IDX_QRTZ_T_C" ON "QRTZ_TRIGGERS"("SCHED_NAME" ASC,"CALENDAR_NAME" ASC) STORAGE(ON "MAIN", CLUSTERBTR) ;
CREATE  INDEX "IDX_QRTZ_T_G" ON "QRTZ_TRIGGERS"("SCHED_NAME" ASC,"TRIGGER_GROUP" ASC) STORAGE(ON "MAIN", CLUSTERBTR) ;
CREATE  INDEX "IDX_QRTZ_T_J" ON "QRTZ_TRIGGERS"("SCHED_NAME" ASC,"JOB_NAME" ASC,"JOB_GROUP" ASC) STORAGE(ON "MAIN", CLUSTERBTR) ;
CREATE  INDEX "IDX_QRTZ_T_JG" ON "QRTZ_TRIGGERS"("SCHED_NAME" ASC,"JOB_GROUP" ASC) STORAGE(ON "MAIN", CLUSTERBTR) ;
CREATE  INDEX "IDX_QRTZ_T_NEXT_FIRE_TIME" ON "QRTZ_TRIGGERS"("SCHED_NAME" ASC,"NEXT_FIRE_TIME" ASC) STORAGE(ON "MAIN", CLUSTERBTR) ;
CREATE  INDEX "IDX_QRTZ_T_NFT_MISFIRE" ON "QRTZ_TRIGGERS"("SCHED_NAME" ASC,"MISFIRE_INSTR" ASC,"NEXT_FIRE_TIME" ASC) STORAGE(ON "MAIN", CLUSTERBTR) ;
CREATE  INDEX "IDX_QRTZ_T_NFT_ST" ON "QRTZ_TRIGGERS"("SCHED_NAME" ASC,"TRIGGER_STATE" ASC,"NEXT_FIRE_TIME" ASC) STORAGE(ON "MAIN", CLUSTERBTR) ;
CREATE  INDEX "IDX_QRTZ_T_NFT_ST_MISFIRE" ON "QRTZ_TRIGGERS"("SCHED_NAME" ASC,"MISFIRE_INSTR" ASC,"NEXT_FIRE_TIME" ASC,"TRIGGER_STATE" ASC) STORAGE(ON "MAIN", CLUSTERBTR) ;
CREATE  INDEX "IDX_QRTZ_T_NFT_ST_MISFIRE_GRP" ON "QRTZ_TRIGGERS"("SCHED_NAME" ASC,"MISFIRE_INSTR" ASC,"NEXT_FIRE_TIME" ASC,"TRIGGER_GROUP" ASC,"TRIGGER_STATE" ASC) STORAGE(ON "MAIN", CLUSTERBTR) ;
CREATE  INDEX "IDX_QRTZ_T_N_G_STATE" ON "QRTZ_TRIGGERS"("SCHED_NAME" ASC,"TRIGGER_GROUP" ASC,"TRIGGER_STATE" ASC) STORAGE(ON "MAIN", CLUSTERBTR) ;
CREATE  INDEX "IDX_QRTZ_T_N_STATE" ON "QRTZ_TRIGGERS"("SCHED_NAME" ASC,"TRIGGER_NAME" ASC,"TRIGGER_GROUP" ASC,"TRIGGER_STATE" ASC) STORAGE(ON "MAIN", CLUSTERBTR) ;
CREATE  INDEX "IDX_QRTZ_T_STATE" ON "QRTZ_TRIGGERS"("SCHED_NAME" ASC,"TRIGGER_STATE" ASC) STORAGE(ON "MAIN", CLUSTERBTR) ;

CREATE TABLE "QRTZ_BLOB_TRIGGERS"
(
"SCHED_NAME" VARCHAR2(120) NOT NULL,
"TRIGGER_NAME" VARCHAR2(200) NOT NULL,
"TRIGGER_GROUP" VARCHAR2(200) NOT NULL,
"BLOB_DATA" BLOB,
CONSTRAINT "QRTZ_BLOB_TRIG_PK" NOT CLUSTER PRIMARY KEY("SCHED_NAME", "TRIGGER_NAME", "TRIGGER_GROUP"),
CONSTRAINT "QRTZ_BLOB_TRIG_TO_TRIG_FK" FOREIGN KEY("SCHED_NAME", "TRIGGER_NAME", "TRIGGER_GROUP") REFERENCES "QRTZ_TRIGGERS"("SCHED_NAME", "TRIGGER_NAME", "TRIGGER_GROUP")) STORAGE(ON "MAIN", CLUSTERBTR) ;

CREATE TABLE "QRTZ_CALENDARS"
(
"SCHED_NAME" VARCHAR2(120) NOT NULL,
"CALENDAR_NAME" VARCHAR2(200) NOT NULL,
"CALENDAR" BLOB NOT NULL,
CONSTRAINT "QRTZ_CALENDARS_PK" NOT CLUSTER PRIMARY KEY("SCHED_NAME", "CALENDAR_NAME")) STORAGE(ON "MAIN", CLUSTERBTR) ;

CREATE TABLE "QRTZ_CRON_TRIGGERS"
(
"SCHED_NAME" VARCHAR2(120) NOT NULL,
"TRIGGER_NAME" VARCHAR2(200) NOT NULL,
"TRIGGER_GROUP" VARCHAR2(200) NOT NULL,
"CRON_EXPRESSION" VARCHAR2(120) NOT NULL,
"TIME_ZONE_ID" VARCHAR2(80),
CONSTRAINT "QRTZ_CRON_TRIG_PK" NOT CLUSTER PRIMARY KEY("SCHED_NAME", "TRIGGER_NAME", "TRIGGER_GROUP"),
CONSTRAINT "QRTZ_CRON_TRIG_TO_TRIG_FK" FOREIGN KEY("SCHED_NAME", "TRIGGER_NAME", "TRIGGER_GROUP") REFERENCES "QRTZ_TRIGGERS"("SCHED_NAME", "TRIGGER_NAME", "TRIGGER_GROUP")) STORAGE(ON "MAIN", CLUSTERBTR) ;

CREATE TABLE "QRTZ_FIRED_TRIGGERS"
(
"SCHED_NAME" VARCHAR2(120) NOT NULL,
"ENTRY_ID" VARCHAR2(95) NOT NULL,
"TRIGGER_NAME" VARCHAR2(200) NOT NULL,
"TRIGGER_GROUP" VARCHAR2(200) NOT NULL,
"INSTANCE_NAME" VARCHAR2(200) NOT NULL,
"FIRED_TIME" NUMBER(13,0) NOT NULL,
"SCHED_TIME" NUMBER(13,0) NOT NULL,
"PRIORITY" NUMBER(13,0) NOT NULL,
"STATE" VARCHAR2(16) NOT NULL,
"JOB_NAME" VARCHAR2(200),
"JOB_GROUP" VARCHAR2(200),
"IS_NONCONCURRENT" VARCHAR2(1),
"REQUESTS_RECOVERY" VARCHAR2(1),
CONSTRAINT "QRTZ_FIRED_TRIGGER_PK" NOT CLUSTER PRIMARY KEY("SCHED_NAME", "ENTRY_ID")) STORAGE(ON "MAIN", CLUSTERBTR) ;
CREATE  INDEX "IDX_QRTZ_FT_INST_JOB_REQ_RCVRY" ON "QRTZ_FIRED_TRIGGERS"("SCHED_NAME" ASC,"INSTANCE_NAME" ASC,"REQUESTS_RECOVERY" ASC) STORAGE(ON "MAIN", CLUSTERBTR) ;
CREATE  INDEX "IDX_QRTZ_FT_JG" ON "QRTZ_FIRED_TRIGGERS"("SCHED_NAME" ASC,"JOB_GROUP" ASC) STORAGE(ON "MAIN", CLUSTERBTR) ;
CREATE  INDEX "IDX_QRTZ_FT_J_G" ON "QRTZ_FIRED_TRIGGERS"("SCHED_NAME" ASC,"JOB_NAME" ASC,"JOB_GROUP" ASC) STORAGE(ON "MAIN", CLUSTERBTR) ;
CREATE  INDEX "IDX_QRTZ_FT_TG" ON "QRTZ_FIRED_TRIGGERS"("SCHED_NAME" ASC,"TRIGGER_GROUP" ASC) STORAGE(ON "MAIN", CLUSTERBTR) ;
CREATE  INDEX "IDX_QRTZ_FT_TRIG_INST_NAME" ON "QRTZ_FIRED_TRIGGERS"("SCHED_NAME" ASC,"INSTANCE_NAME" ASC) STORAGE(ON "MAIN", CLUSTERBTR) ;
CREATE  INDEX "IDX_QRTZ_FT_T_G" ON "QRTZ_FIRED_TRIGGERS"("SCHED_NAME" ASC,"TRIGGER_NAME" ASC,"TRIGGER_GROUP" ASC) STORAGE(ON "MAIN", CLUSTERBTR) ;



CREATE TABLE "QRTZ_JOB_LOG"
(
"LOG_ID" VARCHAR2(17) NOT NULL,
"JOB_NAME" VARCHAR2(200) NOT NULL,
"ADDRESS" VARCHAR2(200) NOT NULL,
"SERVICE_ID" VARCHAR2(200) NOT NULL,
"FIRED_TIME" TIMESTAMP(0) NOT NULL,
"SUCCESS" VARCHAR2(6) NOT NULL,
"LOG_MSG" VARCHAR2(255),
CONSTRAINT "QRTZ_JOB_LOG_PK" NOT CLUSTER PRIMARY KEY("LOG_ID")) STORAGE(ON "MAIN", CLUSTERBTR) ;
COMMENT ON TABLE "QRTZ_JOB_LOG" IS 'Quartz��ʱ����ִ����־';
COMMENT ON COLUMN "QRTZ_JOB_LOG"."ADDRESS" IS '��������ַ';
COMMENT ON COLUMN "QRTZ_JOB_LOG"."FIRED_TIME" IS '����ʱ��';
COMMENT ON COLUMN "QRTZ_JOB_LOG"."JOB_NAME" IS '��������';
COMMENT ON COLUMN "QRTZ_JOB_LOG"."LOG_ID" IS '��־���к�';
COMMENT ON COLUMN "QRTZ_JOB_LOG"."LOG_MSG" IS '��־��Ϣ';
COMMENT ON COLUMN "QRTZ_JOB_LOG"."SERVICE_ID" IS '����ID';
COMMENT ON COLUMN "QRTZ_JOB_LOG"."SUCCESS" IS '�ɹ���־';


CREATE TABLE "QRTZ_JOB_MSGS"
(
"ID" VARCHAR2(50) NOT NULL,
"JOBID" VARCHAR2(80) NOT NULL,
"JOB_GROUP" VARCHAR2(80) NOT NULL,
"USERID" VARCHAR2(20),
"EXECSTARTTIME" VARCHAR2(30),
"EXECENDTIME" VARCHAR2(30),
"ISSUCCESS" VARCHAR2(2),
"SUCCESSMSG" VARCHAR2(1024),
"ERRORMSG" VARCHAR2(1024),
CONSTRAINT "SYS_C0052264" NOT CLUSTER PRIMARY KEY("ID")) STORAGE(ON "MAIN", CLUSTERBTR) ;

CREATE TABLE "QRTZ_LOCKS"
(
"SCHED_NAME" VARCHAR2(120) NOT NULL,
"LOCK_NAME" VARCHAR2(40) NOT NULL,
CONSTRAINT "QRTZ_LOCKS_PK" NOT CLUSTER PRIMARY KEY("SCHED_NAME", "LOCK_NAME")) STORAGE(ON "MAIN", CLUSTERBTR) ;

CREATE TABLE "QRTZ_PAUSED_TRIGGER_GRPS"
(
"SCHED_NAME" VARCHAR2(120) NOT NULL,
"TRIGGER_GROUP" VARCHAR2(200) NOT NULL,
CONSTRAINT "QRTZ_PAUSED_TRIG_GRPS_PK" NOT CLUSTER PRIMARY KEY("SCHED_NAME", "TRIGGER_GROUP")) STORAGE(ON "MAIN", CLUSTERBTR) ;

CREATE TABLE "QRTZ_SCHEDULER_STATE"
(
"SCHED_NAME" VARCHAR2(120) NOT NULL,
"INSTANCE_NAME" VARCHAR2(200) NOT NULL,
"LAST_CHECKIN_TIME" NUMBER(13,0) NOT NULL,
"CHECKIN_INTERVAL" NUMBER(13,0) NOT NULL,
CONSTRAINT "QRTZ_SCHEDULER_STATE_PK" NOT CLUSTER PRIMARY KEY("SCHED_NAME", "INSTANCE_NAME")) STORAGE(ON "MAIN", CLUSTERBTR) ;

CREATE TABLE "QRTZ_SIMPLE_TRIGGERS"
(
"SCHED_NAME" VARCHAR2(120) NOT NULL,
"TRIGGER_NAME" VARCHAR2(200) NOT NULL,
"TRIGGER_GROUP" VARCHAR2(200) NOT NULL,
"REPEAT_COUNT" NUMBER(7,0) NOT NULL,
"REPEAT_INTERVAL" NUMBER(12,0) NOT NULL,
"TIMES_TRIGGERED" NUMBER(10,0) NOT NULL,
CONSTRAINT "QRTZ_SIMPLE_TRIG_PK" NOT CLUSTER PRIMARY KEY("SCHED_NAME", "TRIGGER_NAME", "TRIGGER_GROUP"),
CONSTRAINT "QRTZ_SIMPLE_TRIG_TO_TRIG_FK" FOREIGN KEY("SCHED_NAME", "TRIGGER_NAME", "TRIGGER_GROUP") REFERENCES "QRTZ_TRIGGERS"("SCHED_NAME", "TRIGGER_NAME", "TRIGGER_GROUP")) STORAGE(ON "MAIN", CLUSTERBTR) ;

CREATE TABLE "QRTZ_SIMPROP_TRIGGERS"
(
"SCHED_NAME" VARCHAR2(120) NOT NULL,
"TRIGGER_NAME" VARCHAR2(200) NOT NULL,
"TRIGGER_GROUP" VARCHAR2(200) NOT NULL,
"STR_PROP_1" VARCHAR2(512),
"STR_PROP_2" VARCHAR2(512),
"STR_PROP_3" VARCHAR2(512),
"INT_PROP_1" NUMBER(10,0),
"INT_PROP_2" NUMBER(10,0),
"LONG_PROP_1" NUMBER(13,0),
"LONG_PROP_2" NUMBER(13,0),
"DEC_PROP_1" NUMBER(13,4),
"DEC_PROP_2" NUMBER(13,4),
"BOOL_PROP_1" VARCHAR2(1),
"BOOL_PROP_2" VARCHAR2(1),
CONSTRAINT "QRTZ_SIMPROP_TRIG_PK" NOT CLUSTER PRIMARY KEY("SCHED_NAME", "TRIGGER_NAME", "TRIGGER_GROUP"),
CONSTRAINT "QRTZ_SIMPROP_TRIG_TO_TRIG_FK" FOREIGN KEY("SCHED_NAME", "TRIGGER_NAME", "TRIGGER_GROUP") REFERENCES "QRTZ_TRIGGERS"("SCHED_NAME", "TRIGGER_NAME", "TRIGGER_GROUP")) STORAGE(ON "MAIN", CLUSTERBTR) ;


CREATE TABLE "REGION2016"
(
"REGIONCODE" VARCHAR2(60) NOT NULL,
"REGIONNAME" VARCHAR2(200),
"REGIONPID" VARCHAR2(60),
"REGIONTYPE" VARCHAR2(6),
CONSTRAINT "PK_REGION2016" NOT CLUSTER PRIMARY KEY("REGIONCODE")) STORAGE(ON "MAIN", CLUSTERBTR) ;
COMMENT ON TABLE "REGION2016" IS '����ͳ������������ͳ��绮�ִ��루2016�棩';
COMMENT ON COLUMN "REGION2016"."REGIONCODE" IS '��������';
COMMENT ON COLUMN "REGION2016"."REGIONNAME" IS '������';
COMMENT ON COLUMN "REGION2016"."REGIONPID" IS '��������';
COMMENT ON COLUMN "REGION2016"."REGIONTYPE" IS '��������';


CREATE TABLE "SERVERADDRESS"
(
"ADDRESS" VARCHAR2(200) NOT NULL,
"CANUSE" VARCHAR2(1),
CONSTRAINT "PK_SERVERADDRESS" NOT CLUSTER PRIMARY KEY("ADDRESS")) STORAGE(ON "MAIN", CLUSTERBTR) ;
COMMENT ON TABLE "SERVERADDRESS" IS '��Ⱥ����SERVER��Ӧ�õ�ַ';
COMMENT ON COLUMN "SERVERADDRESS"."ADDRESS" IS 'Ӧ�õ�ַ';
COMMENT ON COLUMN "SERVERADDRESS"."CANUSE" IS '�Ƿ�����';


CREATE TABLE "SIGNRECORD"
(
"USERID" NUMBER(10,0),
"SIGNTIME" TIMESTAMP(0),
"SIGNSTATE" VARCHAR2(2),
"IP" VARCHAR2(20),
"MAC" VARCHAR2(20),
"SIGNID" NUMBER(20,0) NOT NULL) STORAGE(ON "MAIN", CLUSTERBTR) ;
COMMENT ON TABLE "SIGNRECORD" IS 'ǩ��ǩ�˼�¼��';
COMMENT ON COLUMN "SIGNRECORD"."IP" IS 'IP ��ַ';
COMMENT ON COLUMN "SIGNRECORD"."MAC" IS 'MAC��ַ';
COMMENT ON COLUMN "SIGNRECORD"."SIGNID" IS '��ˮ��';
COMMENT ON COLUMN "SIGNRECORD"."SIGNSTATE" IS 'ǩ��״̬(1 ǩ�� 2 ǩ��)';
COMMENT ON COLUMN "SIGNRECORD"."SIGNTIME" IS 'ǩ��ʱ��';
COMMENT ON COLUMN "SIGNRECORD"."USERID" IS '��ԱID';


CREATE TABLE "TAACCESSLOG"
(
"LOGID" NUMBER(15,0) NOT NULL,
"USERID" NUMBER(10,0) NOT NULL,
"POSITIONID" NUMBER(10,0) NOT NULL,
"PERMISSIONID" NUMBER(10,0) NOT NULL,
"ISPERMISSION" CHAR(1) NOT NULL,
"ACCESSTIME" TIMESTAMP(0) NOT NULL,
"URL" VARCHAR2(1024),
"SYSFLAG" VARCHAR2(50),
CONSTRAINT "PK_TAACCESSLOG" NOT CLUSTER PRIMARY KEY("LOGID")) STORAGE(ON "MAIN", CLUSTERBTR) ;
COMMENT ON TABLE "TAACCESSLOG" IS '������־��';
COMMENT ON COLUMN "TAACCESSLOG"."ACCESSTIME" IS '����ʱ��';
COMMENT ON COLUMN "TAACCESSLOG"."ISPERMISSION" IS '�Ƿ���Ȩ��';
COMMENT ON COLUMN "TAACCESSLOG"."LOGID" IS '��־id';
COMMENT ON COLUMN "TAACCESSLOG"."PERMISSIONID" IS '����id';
COMMENT ON COLUMN "TAACCESSLOG"."POSITIONID" IS '��λid';
COMMENT ON COLUMN "TAACCESSLOG"."SYSFLAG" IS 'ϵͳ��ʶ';
COMMENT ON COLUMN "TAACCESSLOG"."URL" IS '����·��';
COMMENT ON COLUMN "TAACCESSLOG"."USERID" IS '�û�id';


CREATE TABLE "TAACCESSSYSTEM"
(
"SYSID" NUMBER(11,0) NOT NULL,
"SYSTEMKEY" VARCHAR2(40) NOT NULL,
"SYSTEMNAME" VARCHAR2(100) NOT NULL,
"PRIVATEKEY" BLOB,
"PUBLICKEY" BLOB,
CONSTRAINT "SYS_C0092209" NOT CLUSTER PRIMARY KEY("SYSID"),
CONSTRAINT "UK_TAACCESSSYSTEM" UNIQUE("SYSTEMKEY")) STORAGE(ON "MAIN", CLUSTERBTR) ;
COMMENT ON TABLE "TAACCESSSYSTEM" IS '����ϵͳ����';
COMMENT ON COLUMN "TAACCESSSYSTEM"."PRIVATEKEY" IS '˽Կ';
COMMENT ON COLUMN "TAACCESSSYSTEM"."PUBLICKEY" IS '��Կ';
COMMENT ON COLUMN "TAACCESSSYSTEM"."SYSID" IS '����ϵͳID';
COMMENT ON COLUMN "TAACCESSSYSTEM"."SYSTEMKEY" IS '�����ʶ';
COMMENT ON COLUMN "TAACCESSSYSTEM"."SYSTEMNAME" IS 'ϵͳ����';


CREATE TABLE "TAADMINYAB139SCOPE"
(
"POSITIONID" NUMBER(10,0) NOT NULL,
"YAB139" VARCHAR2(6) NOT NULL,
CONSTRAINT "PK_TAADMINYAB139SCOPE" NOT CLUSTER PRIMARY KEY("POSITIONID", "YAB139")) STORAGE(ON "MAIN", CLUSTERBTR) ;
COMMENT ON TABLE "TAADMINYAB139SCOPE" IS '����Ա����������Χ';
COMMENT ON COLUMN "TAADMINYAB139SCOPE"."POSITIONID" IS '��λid';
COMMENT ON COLUMN "TAADMINYAB139SCOPE"."YAB139" IS '������';


CREATE TABLE "TACOMMONMENU"
(
"USERID" NUMBER(10,0) NOT NULL,
"MENUID" NUMBER(10,0) NOT NULL,
CONSTRAINT "PK_TACOMMONMENU" NOT CLUSTER PRIMARY KEY("USERID", "MENUID")) STORAGE(ON "MAIN", CLUSTERBTR) ;
COMMENT ON TABLE "TACOMMONMENU" IS '���ò˵�';
COMMENT ON COLUMN "TACOMMONMENU"."MENUID" IS '�˵�id';
COMMENT ON COLUMN "TACOMMONMENU"."USERID" IS '�û�id';


CREATE TABLE "TACONFIG"
(
"CONFIGID" NUMBER(10,0) NOT NULL,
"CONFIGNAME" VARCHAR2(100) NOT NULL,
"CONFIGVALUE" VARCHAR2(1024),
"CONFIGTYPE" VARCHAR2(1024),
"CONFIGFLAG" VARCHAR2(20) NOT NULL,
"CONFIGDESC" VARCHAR2(200),
CONSTRAINT "PK_TACONFIG" NOT CLUSTER PRIMARY KEY("CONFIGID")) STORAGE(ON "MAIN", CLUSTERBTR) ;
COMMENT ON TABLE "TACONFIG" IS 'ϵͳ���ñ�';
COMMENT ON COLUMN "TACONFIG"."CONFIGDESC" IS '����˵��';
COMMENT ON COLUMN "TACONFIG"."CONFIGFLAG" IS 'ϵͳ��ʶ';
COMMENT ON COLUMN "TACONFIG"."CONFIGID" IS '������ID';
COMMENT ON COLUMN "TACONFIG"."CONFIGNAME" IS '����������';
COMMENT ON COLUMN "TACONFIG"."CONFIGTYPE" IS '�Ƿ�ϵͳ����';
COMMENT ON COLUMN "TACONFIG"."CONFIGVALUE" IS '����������';


CREATE TABLE "TACONFIGSYSPATH"
(
"SERIALID" NUMBER(10,0) NOT NULL,
"ID" VARCHAR2(20) NOT NULL,
"NAME" VARCHAR2(50) NOT NULL,
"URL" VARCHAR2(100) NOT NULL,
"PY" VARCHAR2(20),
"CURSYSTEM" VARCHAR2(1) NOT NULL,
CONSTRAINT "SYS_C0091994" NOT CLUSTER PRIMARY KEY("SERIALID")) STORAGE(ON "MAIN", CLUSTERBTR) ;
COMMENT ON TABLE "TACONFIGSYSPATH" IS 'ϵͳ·�����ñ�';
COMMENT ON COLUMN "TACONFIGSYSPATH"."CURSYSTEM" IS '�Ƿ�Ϊ��ǰϵͳ';
COMMENT ON COLUMN "TACONFIGSYSPATH"."ID" IS 'ϵͳID';
COMMENT ON COLUMN "TACONFIGSYSPATH"."NAME" IS 'ϵͳ����';
COMMENT ON COLUMN "TACONFIGSYSPATH"."PY" IS 'ƴ��';
COMMENT ON COLUMN "TACONFIGSYSPATH"."SERIALID" IS '��ˮ��';
COMMENT ON COLUMN "TACONFIGSYSPATH"."URL" IS 'ϵͳ·��ǰ׺';


CREATE TABLE "TACONSOLEMODULE"
(
"MODULE_ID" NUMBER(10,0) NOT NULL,
"MODULE_NAME" VARCHAR2(100) NOT NULL,
"MODULE_URL" VARCHAR2(200) NOT NULL,
"MODULE_STA" VARCHAR2(1) DEFAULT '1' NOT NULL,
"MODULE_DEFAULT" VARCHAR2(1) DEFAULT '1',
"MODULE_HEIGHT" VARCHAR2(10) DEFAULT '200',
CONSTRAINT "PK_ECADMIN_CONSLE_MODULE" NOT CLUSTER PRIMARY KEY("MODULE_ID")) STORAGE(ON "MAIN", CLUSTERBTR) ;
COMMENT ON TABLE "TACONSOLEMODULE" IS 'ECADMIN����̨�Զ������';
COMMENT ON COLUMN "TACONSOLEMODULE"."MODULE_DEFAULT" IS '�Ƿ�Ĭ����ʾ';
COMMENT ON COLUMN "TACONSOLEMODULE"."MODULE_HEIGHT" IS 'ģ��Ĭ�ϸ߶�';
COMMENT ON COLUMN "TACONSOLEMODULE"."MODULE_ID" IS 'ģ����';
COMMENT ON COLUMN "TACONSOLEMODULE"."MODULE_NAME" IS 'ģ������';
COMMENT ON COLUMN "TACONSOLEMODULE"."MODULE_STA" IS 'ģ����Ч��ʶ';
COMMENT ON COLUMN "TACONSOLEMODULE"."MODULE_URL" IS 'ģ������';


CREATE TABLE "TACONSOLEMODULELOCATION"
(
"MARK" VARCHAR2(20) NOT NULL,
"POSITIONID" NUMBER(10,0) NOT NULL,
"LOCATION" VARCHAR2(1000) NOT NULL) STORAGE(ON "MAIN", CLUSTERBTR) ;
COMMENT ON TABLE "TACONSOLEMODULELOCATION" IS 'ECADMIN����̨�Զ������λ����Ϣ';
COMMENT ON COLUMN "TACONSOLEMODULELOCATION"."LOCATION" IS 'λ����Ϣ����';
COMMENT ON COLUMN "TACONSOLEMODULELOCATION"."MARK" IS 'ҳ���ʶ';
COMMENT ON COLUMN "TACONSOLEMODULELOCATION"."POSITIONID" IS '��λID';


CREATE TABLE "TACONSOLEMODULEPRIVILEGE"
(
"POSITIONID" NUMBER(10,0) NOT NULL,
"MODULEID" NUMBER(10,0) NOT NULL,
CONSTRAINT "PK_CRM_CONSLE_MODULE_PRIVILEGE" NOT CLUSTER PRIMARY KEY("POSITIONID", "MODULEID")) STORAGE(ON "MAIN", CLUSTERBTR) ;
COMMENT ON TABLE "TACONSOLEMODULEPRIVILEGE" IS 'CRM����̨�Զ������Ȩ����Ϣ';
COMMENT ON COLUMN "TACONSOLEMODULEPRIVILEGE"."MODULEID" IS 'ģ����';
COMMENT ON COLUMN "TACONSOLEMODULEPRIVILEGE"."POSITIONID" IS '��ɫ���';


CREATE TABLE "TADATAACCESSDIMENSION"
(
"DIMENSIONID" NUMBER(10,0) NOT NULL,
"POSITIONID" NUMBER(10,0) NOT NULL,
"MENUID" NUMBER(10,0) NOT NULL,
"DIMENSIONTYPE" VARCHAR2(20) NOT NULL,
"DIMENSIONPERMISSIONID" VARCHAR2(20),
"ALLACCESS" VARCHAR2(1),
"SYSPATH" VARCHAR2(50),
CONSTRAINT "PK_TADATAACCESSDIMENSION" NOT CLUSTER PRIMARY KEY("DIMENSIONID")) STORAGE(ON "MAIN", CLUSTERBTR) ;
COMMENT ON TABLE "TADATAACCESSDIMENSION" IS 'ά������Ȩ�ޱ�';
COMMENT ON COLUMN "TADATAACCESSDIMENSION"."ALLACCESS" IS '�Ƿ���и�ά������Ȩ��';
COMMENT ON COLUMN "TADATAACCESSDIMENSION"."DIMENSIONID" IS 'ά��ID';
COMMENT ON COLUMN "TADATAACCESSDIMENSION"."DIMENSIONPERMISSIONID" IS 'ά��Ȩ��ID';
COMMENT ON COLUMN "TADATAACCESSDIMENSION"."DIMENSIONTYPE" IS 'ά������';
COMMENT ON COLUMN "TADATAACCESSDIMENSION"."MENUID" IS '�˵�ID';
COMMENT ON COLUMN "TADATAACCESSDIMENSION"."POSITIONID" IS '��λID';
COMMENT ON COLUMN "TADATAACCESSDIMENSION"."SYSPATH" IS 'ϵͳ��ʶ';


CREATE TABLE "TAFIELD"
(
"ID" NUMBER(10,0) NOT NULL,
"MENUID" NUMBER(10,0),
"FIELDID" VARCHAR2(100),
"FIELDNAME" VARCHAR2(100),
"TABLEID" VARCHAR2(10),
"PID" NUMBER(10,0),
"FIELDLEVEL" NUMBER) STORAGE(ON "MAIN", CLUSTERBTR) ;
COMMENT ON COLUMN "TAFIELD"."FIELDID" IS '�ֶ�id';
COMMENT ON COLUMN "TAFIELD"."FIELDLEVEL" IS '�ֶβ㼶';
COMMENT ON COLUMN "TAFIELD"."FIELDNAME" IS '�ֶ�����';
COMMENT ON COLUMN "TAFIELD"."ID" IS '����';
COMMENT ON COLUMN "TAFIELD"."MENUID" IS '�˵�ID';
COMMENT ON COLUMN "TAFIELD"."PID" IS '���ڵ�Id';
COMMENT ON COLUMN "TAFIELD"."TABLEID" IS '��id(����)';


CREATE TABLE "TAFIELDAUTHRITY"
(
"POSITIONID" NUMBER(10,0) NOT NULL,
"MENUID" NUMBER(10,0) NOT NULL,
"FIELDID" VARCHAR2(100) NOT NULL,
"LOOK" CHAR(1),
"EDIT" CHAR(1),
"CREATETIME" TIMESTAMP(0),
"CREATEUSER" NUMBER(10,0)) STORAGE(ON "MAIN", CLUSTERBTR) ;
COMMENT ON COLUMN "TAFIELDAUTHRITY"."CREATETIME" IS '����ʱ��';
COMMENT ON COLUMN "TAFIELDAUTHRITY"."CREATEUSER" IS '������';
COMMENT ON COLUMN "TAFIELDAUTHRITY"."EDIT" IS '�Ƿ�ɱ༭��1���ɱ༭��0�����ɲ鿴��';
COMMENT ON COLUMN "TAFIELDAUTHRITY"."FIELDID" IS '�ֶ�id';
COMMENT ON COLUMN "TAFIELDAUTHRITY"."LOOK" IS '�Ƿ�ɲ鿴��1���ɲ鿴��0���ɲ鿴��';
COMMENT ON COLUMN "TAFIELDAUTHRITY"."MENUID" IS '�˵�id';
COMMENT ON COLUMN "TAFIELDAUTHRITY"."POSITIONID" IS '��λid';


CREATE TABLE "TALIMITRATE"
(
"MENUID" NUMBER(10,0) NOT NULL,
"LIMITOPEN" CHAR(1) NOT NULL,
"RATE" NUMBER(16,2) NOT NULL,
"TIMEOUT" NUMBER(38,0) NOT NULL,
"MAXCOUNT" NUMBER(10,0) NOT NULL,
"URL" VARCHAR2(100) NOT NULL,
CONSTRAINT "PK_TALIMITRATE" NOT CLUSTER PRIMARY KEY("URL")) STORAGE(ON "MAIN", CLUSTERBTR) ;
COMMENT ON TABLE "TALIMITRATE" IS '��������';
COMMENT ON COLUMN "TALIMITRATE"."LIMITOPEN" IS '�Ƿ�������';
COMMENT ON COLUMN "TALIMITRATE"."MAXCOUNT" IS '������ʵ���󲢷���';
COMMENT ON COLUMN "TALIMITRATE"."MENUID" IS '�˵�id';
COMMENT ON COLUMN "TALIMITRATE"."RATE" IS '����ķ���Ƶ��';
COMMENT ON COLUMN "TALIMITRATE"."TIMEOUT" IS '��ȡ������ɵĳ�ʱʱ��';
COMMENT ON COLUMN "TALIMITRATE"."URL" IS '����·��';


CREATE TABLE "TALOCALCACHEVERSION"
(
"VERSION" NUMBER(11,0) NOT NULL,
"CODETYPE" VARCHAR2(20)) STORAGE(ON "MAIN", CLUSTERBTR) ;
COMMENT ON TABLE "TALOCALCACHEVERSION" IS '���ػ������汾��';
COMMENT ON COLUMN "TALOCALCACHEVERSION"."CODETYPE" IS '�Ķ���type';
COMMENT ON COLUMN "TALOCALCACHEVERSION"."VERSION" IS '�汾��';


CREATE TABLE "TALOGINHISTORYLOG"
(
"LOGID" NUMBER(15,0) NOT NULL,
"USERID" NUMBER(10,0) NOT NULL,
"LOGINTIME" TIMESTAMP(0) NOT NULL,
"LOGOUTTIME" TIMESTAMP(0) NOT NULL,
"CLIENTIP" VARCHAR2(200) NOT NULL,
"SESSIONID" VARCHAR2(200) NOT NULL,
"SERVERIP" VARCHAR2(200),
"SYSPATH" VARCHAR2(50),
"CLIENTSYSTEM" VARCHAR2(50),
"CLIENTBROWSER" VARCHAR2(50),
"CLIENTSCREENSIZE" VARCHAR2(50),
CONSTRAINT "PK_TALOGINHISTORYLOG" NOT CLUSTER PRIMARY KEY("LOGID")) STORAGE(ON "MAIN", CLUSTERBTR) ;

CREATE TABLE "TAMANAGERMG"
(
"POSITIONID" NUMBER(10,0),
"ORGID" NUMBER(10,0)) STORAGE(ON "MAIN", CLUSTERBTR) ;
COMMENT ON TABLE "TAMANAGERMG" IS '��֯�����ˣ���ְ�������';
COMMENT ON COLUMN "TAMANAGERMG"."ORGID" IS '��֯id';
COMMENT ON COLUMN "TAMANAGERMG"."POSITIONID" IS '��λid';


CREATE TABLE "TAMENU"
(
"MENUID" NUMBER(10,0) NOT NULL,
"PMENUID" NUMBER(10,0) NOT NULL,
"MENUNAME" VARCHAR2(60),
"URL" VARCHAR2(100),
"MENUIDPATH" VARCHAR2(1024),
"MENUNAMEPATH" VARCHAR2(1024),
"ICONSKIN" VARCHAR2(200),
"SELECTIMAGE" VARCHAR2(200),
"REPORTID" VARCHAR2(50),
"ACCESSTIMEEL" VARCHAR2(200),
"EFFECTIVE" CHAR(1) NOT NULL,
"SECURITYPOLICY" CHAR(1) NOT NULL,
"ISDISMULTIPOS" CHAR(1) NOT NULL,
"QUICKCODE" VARCHAR2(20),
"SORTNO" NUMBER,
"RESOURCETYPE" CHAR(2) NOT NULL,
"MENULEVEL" NUMBER,
"ISLEAF" CHAR(1),
"MENUTYPE" CHAR(1),
"ISCACHE" CHAR(1),
"SYSPATH" VARCHAR2(20),
"USEYAB003" CHAR(1),
"TYPEFLAG" NUMBER(10,0),
"ISAUDITE" VARCHAR2(1),
"CONSOLEMODULE" CHAR(1) DEFAULT '1',
"CUSTOMENCODING" VARCHAR2(20),
"ISFILEDSCONTROL" CHAR(1) DEFAULT '1',
CONSTRAINT "PK_TAMENU" NOT CLUSTER PRIMARY KEY("MENUID")) STORAGE(ON "MAIN", CLUSTERBTR) ;
COMMENT ON TABLE "TAMENU" IS '���ܲ˵�';
COMMENT ON COLUMN "TAMENU"."ACCESSTIMEEL" IS '��������ʱ����ʽ';
COMMENT ON COLUMN "TAMENU"."CONSOLEMODULE" IS '�Ƿ�Ϊ����̨ģ��';
COMMENT ON COLUMN "TAMENU"."CUSTOMENCODING" IS '�Զ������';
COMMENT ON COLUMN "TAMENU"."EFFECTIVE" IS '��Ч��־';
COMMENT ON COLUMN "TAMENU"."ICONSKIN" IS 'ѡ��ǰͼƬ';
COMMENT ON COLUMN "TAMENU"."ISAUDITE" IS '�Ƿ���Ҫ���';
COMMENT ON COLUMN "TAMENU"."ISCACHE" IS '�Ƿ񻺴�';
COMMENT ON COLUMN "TAMENU"."ISDISMULTIPOS" IS '�Ƿ���ʾ���';
COMMENT ON COLUMN "TAMENU"."ISFILEDSCONTROL" IS '�Ƿ���Ҫ�ֶ�Ȩ�޿���';
COMMENT ON COLUMN "TAMENU"."ISLEAF" IS '�Ƿ�Ҷ�ӽڵ�';
COMMENT ON COLUMN "TAMENU"."MENUID" IS '�˵�Id';
COMMENT ON COLUMN "TAMENU"."MENUIDPATH" IS '�˵�id·��';
COMMENT ON COLUMN "TAMENU"."MENULEVEL" IS '�˵��㼶';
COMMENT ON COLUMN "TAMENU"."MENUNAME" IS '���ܵ�ַ';
COMMENT ON COLUMN "TAMENU"."MENUNAMEPATH" IS '�˵�����·��';
COMMENT ON COLUMN "TAMENU"."MENUTYPE" IS '�˵�����';
COMMENT ON COLUMN "TAMENU"."PMENUID" IS '���˵�id';
COMMENT ON COLUMN "TAMENU"."QUICKCODE" IS '��ݷ�����';
COMMENT ON COLUMN "TAMENU"."REPORTID" IS '��ѯ����ı���id';
COMMENT ON COLUMN "TAMENU"."RESOURCETYPE" IS 'Ȩ�����ͣ�����Ȩ��\��ťȨ��\��ֻ��\���ɱ༭\�����ֻ��\����пɱ༭��';
COMMENT ON COLUMN "TAMENU"."SECURITYPOLICY" IS '��ȫ����';
COMMENT ON COLUMN "TAMENU"."SELECTIMAGE" IS 'ѡ���ͼƬ';
COMMENT ON COLUMN "TAMENU"."SORTNO" IS '�����';
COMMENT ON COLUMN "TAMENU"."SYSPATH" IS 'ϵͳ·��';
COMMENT ON COLUMN "TAMENU"."TYPEFLAG" IS '���ʶ';
COMMENT ON COLUMN "TAMENU"."URL" IS '��������';
COMMENT ON COLUMN "TAMENU"."USEYAB003" IS '�Ƿ����÷���������Ȩ��';


CREATE TABLE "TAMENUPOSITIONYAB003"
(
"MENUID" NUMBER(10,0) NOT NULL,
"POSITIONID" NUMBER(10,0) NOT NULL,
"YAB003" VARCHAR2(6) NOT NULL,
CONSTRAINT "PK_TAMENUPOSITIONYAB003" NOT CLUSTER PRIMARY KEY("MENUID", "POSITIONID", "YAB003")) STORAGE(ON "MAIN", CLUSTERBTR) ;
COMMENT ON TABLE "TAMENUPOSITIONYAB003" IS '��������Ȩ��';
COMMENT ON COLUMN "TAMENUPOSITIONYAB003"."MENUID" IS '�˵�id';
COMMENT ON COLUMN "TAMENUPOSITIONYAB003"."POSITIONID" IS '��λid';
COMMENT ON COLUMN "TAMENUPOSITIONYAB003"."YAB003" IS '������';


CREATE TABLE "TAMESSAGE"
(
"USERID" NUMBER(10,0),
"ORGID" NUMBER(10,0) NOT NULL,
"SIGN" VARCHAR2(6) DEFAULT '0',
"MGID" VARCHAR2(20) NOT NULL,
"MGDATE" TIMESTAMP(6),
"TITLE" VARCHAR2(100),
"CONTENT" CLOB,
"MGCHECK" VARCHAR2(1) DEFAULT '0',
CONSTRAINT "ID" NOT CLUSTER PRIMARY KEY("MGID", "ORGID")) STORAGE(ON "MAIN", CLUSTERBTR) ;
COMMENT ON COLUMN "TAMESSAGE"."CONTENT" IS '֪ͨ����';
COMMENT ON COLUMN "TAMESSAGE"."MGCHECK" IS '0δ���/aͨ��/b��ͨ��';
COMMENT ON COLUMN "TAMESSAGE"."MGDATE" IS '��������';
COMMENT ON COLUMN "TAMESSAGE"."MGID" IS '��Ϣid';
COMMENT ON COLUMN "TAMESSAGE"."ORGID" IS '������֯';
COMMENT ON COLUMN "TAMESSAGE"."SIGN" IS 'ָ����λ��־';
COMMENT ON COLUMN "TAMESSAGE"."TITLE" IS '֪ͨ����';
COMMENT ON COLUMN "TAMESSAGE"."USERID" IS '������Աid';


CREATE TABLE "TAMESSAGEATTACHMENT"
(
"MGID" VARCHAR2(20) NOT NULL,
"ATTACHMENT" BLOB,
"NAME" VARCHAR2(50)) STORAGE(ON "MAIN", CLUSTERBTR) ;
COMMENT ON COLUMN "TAMESSAGEATTACHMENT"."ATTACHMENT" IS '֪ͨ����';
COMMENT ON COLUMN "TAMESSAGEATTACHMENT"."MGID" IS '��Ϣid';
COMMENT ON COLUMN "TAMESSAGEATTACHMENT"."NAME" IS '��������';


CREATE TABLE "TAMESSAGESTATE"
(
"MGID" VARCHAR2(20) NOT NULL,
"USERID" NUMBER(10,0) NOT NULL,
"STATE" VARCHAR2(6) DEFAULT '0') STORAGE(ON "MAIN", CLUSTERBTR) ;
COMMENT ON COLUMN "TAMESSAGESTATE"."MGID" IS '��Ϣid';
COMMENT ON COLUMN "TAMESSAGESTATE"."STATE" IS '�Ѷ���־';
COMMENT ON COLUMN "TAMESSAGESTATE"."USERID" IS '������Ա';


CREATE TABLE "TAONLINELOG"
(
"LOGID" NUMBER(15,0) NOT NULL,
"USERID" NUMBER(10,0) NOT NULL,
"LOGINTIME" TIMESTAMP(0) NOT NULL,
"CURRESOURCE" VARCHAR2(1000),
"CLIENTIP" VARCHAR2(200) NOT NULL,
"SESSIONID" VARCHAR2(200) NOT NULL,
"SYSPATH" VARCHAR2(50),
"SERVERIP" VARCHAR2(200),
"CLIENTSYSTEM" VARCHAR2(50),
"CLIENTBROWSER" VARCHAR2(50),
"CLIENTSCREENSIZE" VARCHAR2(50),
CONSTRAINT "PK_TAONLINELOG" NOT CLUSTER PRIMARY KEY("LOGID")) STORAGE(ON "MAIN", CLUSTERBTR) ;

CREATE TABLE "TAONLINESTATLOG"
(
"STATDATE" VARCHAR2(20) NOT NULL,
"POINTINTIME" VARCHAR2(20) NOT NULL,
"LOGINNUM" NUMBER(15,0) NOT NULL,
CONSTRAINT "TAONLINESTATLOG" NOT CLUSTER PRIMARY KEY("STATDATE", "POINTINTIME")) STORAGE(ON "MAIN", CLUSTERBTR) ;
COMMENT ON TABLE "TAONLINESTATLOG" IS 'ʱ���¼���ͳ�Ʊ�';
COMMENT ON COLUMN "TAONLINESTATLOG"."LOGINNUM" IS '��������';
COMMENT ON COLUMN "TAONLINESTATLOG"."POINTINTIME" IS 'ͳ��ʱ���';
COMMENT ON COLUMN "TAONLINESTATLOG"."STATDATE" IS 'ͳ������';


CREATE TABLE "TAORG"
(
"ORGID" NUMBER(10,0) NOT NULL,
"PORGID" NUMBER(10,0),
"ORGNAME" VARCHAR2(60),
"COSTOMNO" VARCHAR2(10),
"ORGIDPATH" VARCHAR2(1024),
"ORGNAMEPATH" VARCHAR2(1024),
"COSTOMNOPATH" VARCHAR2(1024),
"ORGTYPE" CHAR(2),
"SORT" NUMBER,
"YAB003" VARCHAR2(6),
"DIMENSION" CHAR(2),
"CREATEUSER" NUMBER(10,0) NOT NULL,
"CREATETIME" TIMESTAMP(0) NOT NULL,
"EFFECTIVE" CHAR(1) NOT NULL,
"ORGLEVEL" NUMBER(10,0),
"ISLEAF" CHAR(1),
"ORGMANAGER" NUMBER(10,0),
"DESTORY" CHAR(1),
"TYPEFLAG" NUMBER(10,0),
"YAB139" VARCHAR2(6),
CONSTRAINT "PK_TAORG" NOT CLUSTER PRIMARY KEY("ORGID"),
CONSTRAINT "FK_REFERENCE_6" FOREIGN KEY("PORGID") REFERENCES "TAORG"("ORGID") WITH INDEX ) STORAGE(ON "MAIN", CLUSTERBTR) ;
COMMENT ON TABLE "TAORG" IS '��֯��ͼ';
COMMENT ON COLUMN "TAORG"."COSTOMNO" IS '�Զ������';
COMMENT ON COLUMN "TAORG"."COSTOMNOPATH" IS '�Զ������·��';
COMMENT ON COLUMN "TAORG"."CREATETIME" IS '����ʱ��';
COMMENT ON COLUMN "TAORG"."CREATEUSER" IS '������';
COMMENT ON COLUMN "TAORG"."DESTORY" IS '�Ƿ�����';
COMMENT ON COLUMN "TAORG"."DIMENSION" IS '��ͼά��';
COMMENT ON COLUMN "TAORG"."EFFECTIVE" IS '��Ч��';
COMMENT ON COLUMN "TAORG"."ISLEAF" IS '�Ƿ�Ҷ�ӽڵ�';
COMMENT ON COLUMN "TAORG"."ORGID" IS '��֯id';
COMMENT ON COLUMN "TAORG"."ORGIDPATH" IS '��֯id·��';
COMMENT ON COLUMN "TAORG"."ORGLEVEL" IS '��֯�㼶';
COMMENT ON COLUMN "TAORG"."ORGMANAGER" IS '��֯�����ˣ���ְ��';
COMMENT ON COLUMN "TAORG"."ORGNAME" IS '��֯����';
COMMENT ON COLUMN "TAORG"."ORGNAMEPATH" IS '��֯����·��';
COMMENT ON COLUMN "TAORG"."ORGTYPE" IS '��֯���ͣ����������š��ӹ�˾�������š��飩';
COMMENT ON COLUMN "TAORG"."PORGID" IS '��֯��id';
COMMENT ON COLUMN "TAORG"."SORT" IS '�����';
COMMENT ON COLUMN "TAORG"."TYPEFLAG" IS '���ʶ';
COMMENT ON COLUMN "TAORG"."YAB003" IS '�������';
COMMENT ON COLUMN "TAORG"."YAB139" IS '������';





CREATE TABLE "TAORGOPLOG"
(
"LOGID" NUMBER(10,0) NOT NULL,
"BATCHNO" VARCHAR2(10),
"OPTYPE" CHAR(2),
"INFLUENCEBODYTYPE" CHAR(2),
"INFLUENCEBODY" VARCHAR2(10),
"OPBODY" CHAR(2),
"OPSUBJEKT" VARCHAR2(10),
"CHANGCONTENT" VARCHAR2(2048),
"OPTIME" TIMESTAMP(0) NOT NULL,
"OPUSER" VARCHAR2(10) NOT NULL,
"OPPOSITION" VARCHAR2(10) NOT NULL,
"ISPERMISSION" VARCHAR2(1),
CONSTRAINT "PK_TAORGOPLOG" NOT CLUSTER PRIMARY KEY("LOGID")) STORAGE(ON "MAIN", CLUSTERBTR) ;
COMMENT ON TABLE "TAORGOPLOG" IS '��֯��Ȩ�޲�����־';
COMMENT ON COLUMN "TAORGOPLOG"."BATCHNO" IS '�������κ�';
COMMENT ON COLUMN "TAORGOPLOG"."CHANGCONTENT" IS '����������';
COMMENT ON COLUMN "TAORGOPLOG"."INFLUENCEBODY" IS 'Ӱ������';
COMMENT ON COLUMN "TAORGOPLOG"."INFLUENCEBODYTYPE" IS 'Ӱ���������ͣ���֯����Ա����λ����ɫ��Ȩ����Դ��';
COMMENT ON COLUMN "TAORGOPLOG"."ISPERMISSION" IS '�Ƿ���Ȩ��';
COMMENT ON COLUMN "TAORGOPLOG"."LOGID" IS '��־id';
COMMENT ON COLUMN "TAORGOPLOG"."OPBODY" IS '�����������ͣ���Ա����֯����λ����ɫ��Ȩ����Դ��';
COMMENT ON COLUMN "TAORGOPLOG"."OPPOSITION" IS '�����λ';
COMMENT ON COLUMN "TAORGOPLOG"."OPSUBJEKT" IS '��������';
COMMENT ON COLUMN "TAORGOPLOG"."OPTIME" IS '����ʱ��';
COMMENT ON COLUMN "TAORGOPLOG"."OPTYPE" IS '�������ͣ��������༭��ɾ������Ȩ������Ȩ�ޣ�';
COMMENT ON COLUMN "TAORGOPLOG"."OPUSER" IS '������';


CREATE TABLE "TAPAGEREVIEW"
(
"PAGE_ID" NUMBER(20,0) NOT NULL,
"FUNCTION_ID" NUMBER(20,0),
"CREATE_TIME" TIMESTAMP(0),
"CONTEXT" BLOB,
"DATA" BLOB,
"LOG_ID" VARCHAR2(20),
"RESULT_BEAN" BLOB,
CONSTRAINT "PK_PAGE_ID" NOT CLUSTER PRIMARY KEY("PAGE_ID")) STORAGE(ON "MAIN", CLUSTERBTR) ;
COMMENT ON COLUMN "TAPAGEREVIEW"."RESULT_BEAN" IS 'ResultBean��������л�';


CREATE TABLE "TAPOSITION"
(
"POSITIONID" NUMBER(10,0) NOT NULL,
"ORGID" NUMBER(10,0) NOT NULL,
"POSITIONNAME" VARCHAR2(60) NOT NULL,
"POSITIONTYPE" CHAR(1) NOT NULL,
"CREATEPOSITIONID" NUMBER(10,0) NOT NULL,
"ORGIDPATH" VARCHAR2(1024),
"ORGNAMEPATH" VARCHAR2(1024),
"VALIDTIME" TIMESTAMP(0),
"CREATEUSER" NUMBER(10,0) NOT NULL,
"CREATETIME" TIMESTAMP(0) NOT NULL,
"EFFECTIVE" CHAR(1) NOT NULL,
"ISADMIN" CHAR(1),
"ISSHARE" CHAR(1),
"ISCOPY" CHAR(1),
"TYPEFLAG" NUMBER(10,0),
"POSITIONCATEGORY" VARCHAR2(2),
"ISDEVELOPER" VARCHAR2(1),
CONSTRAINT "PK_TAPOSITION" NOT CLUSTER PRIMARY KEY("POSITIONID"),
CONSTRAINT "FK_RELATIONSHIP_5" FOREIGN KEY("ORGID") REFERENCES "TAORG"("ORGID")) STORAGE(ON "MAIN", CLUSTERBTR) ;
COMMENT ON TABLE "TAPOSITION" IS '��λ';
COMMENT ON COLUMN "TAPOSITION"."CREATEPOSITIONID" IS '������ʹ�õĸ�λ';
COMMENT ON COLUMN "TAPOSITION"."CREATETIME" IS '����ʱ��';
COMMENT ON COLUMN "TAPOSITION"."CREATEUSER" IS '������';
COMMENT ON COLUMN "TAPOSITION"."EFFECTIVE" IS '��Ч��־';
COMMENT ON COLUMN "TAPOSITION"."ISADMIN" IS '�Ƿ����Ա';
COMMENT ON COLUMN "TAPOSITION"."ISCOPY" IS '�Ƿ�Ϊ���Ƹ�λ';
COMMENT ON COLUMN "TAPOSITION"."ISDEVELOPER" IS '�Ƿ����Ա';
COMMENT ON COLUMN "TAPOSITION"."ISSHARE" IS '�Ƿ�Ϊ�����λ';
COMMENT ON COLUMN "TAPOSITION"."ORGID" IS '��֯id';
COMMENT ON COLUMN "TAPOSITION"."ORGIDPATH" IS '������֯id·��';
COMMENT ON COLUMN "TAPOSITION"."ORGNAMEPATH" IS '������֯����·��';
COMMENT ON COLUMN "TAPOSITION"."POSITIONCATEGORY" IS '��λ���';
COMMENT ON COLUMN "TAPOSITION"."POSITIONID" IS '��λid';
COMMENT ON COLUMN "TAPOSITION"."POSITIONNAME" IS '��λ����';
COMMENT ON COLUMN "TAPOSITION"."POSITIONTYPE" IS '��λ���ͣ�����ר����λ/���и�λ��';
COMMENT ON COLUMN "TAPOSITION"."TYPEFLAG" IS '���ʶ';
COMMENT ON COLUMN "TAPOSITION"."VALIDTIME" IS 'ֻ���ί�����ɵĸ�λ';

CREATE TABLE "TAORGMG"
(
"POSITIONID" NUMBER(10,0),
"ORGID" NUMBER(10,0),
CONSTRAINT "FK_REFERENCE_8" FOREIGN KEY("ORGID") REFERENCES "TAORG"("ORGID"),
CONSTRAINT "FK_REFERENCE_9" FOREIGN KEY("POSITIONID") REFERENCES "TAPOSITION"("POSITIONID")) STORAGE(ON "MAIN", CLUSTERBTR) ;
COMMENT ON TABLE "TAORGMG" IS '��֯�����';
COMMENT ON COLUMN "TAORGMG"."ORGID" IS '��֯id';
COMMENT ON COLUMN "TAORGMG"."POSITIONID" IS '��λid';

CREATE TABLE "TAPOSITIONAUTHRITY"
(
"POSITIONID" NUMBER(10,0) NOT NULL,
"MENUID" NUMBER(10,0) NOT NULL,
"USEPERMISSION" CHAR(1),
"REPERMISSION" CHAR(1),
"REAUTHRITY" CHAR(1),
"CREATEUSER" NUMBER(10,0) NOT NULL,
"CREATETIME" TIMESTAMP(0) NOT NULL,
"EFFECTTIME" TIMESTAMP(0),
"AUDITEACCESSDATE" TIMESTAMP(0),
"AUDITEUSER" NUMBER(10,0),
"AUDITSTATE" VARCHAR2(1) DEFAULT '0',
CONSTRAINT "PK_TAPOSITIONAUTHRITY" NOT CLUSTER PRIMARY KEY("POSITIONID", "MENUID"),
CONSTRAINT "FK_RELATIONSHIP_11" FOREIGN KEY("POSITIONID") REFERENCES "TAPOSITION"("POSITIONID"),
CONSTRAINT "FK_REFERENCE_7" FOREIGN KEY("MENUID") REFERENCES "TAMENU"("MENUID")) STORAGE(ON "MAIN", CLUSTERBTR) ;
COMMENT ON TABLE "TAPOSITIONAUTHRITY" IS '��λȨ�ޱ�';
COMMENT ON COLUMN "TAPOSITIONAUTHRITY"."AUDITEACCESSDATE" IS '���ͨ��ʱ��';
COMMENT ON COLUMN "TAPOSITIONAUTHRITY"."AUDITEUSER" IS '�����';
COMMENT ON COLUMN "TAPOSITIONAUTHRITY"."AUDITSTATE" IS '���״̬';
COMMENT ON COLUMN "TAPOSITIONAUTHRITY"."CREATETIME" IS '����ʱ��';
COMMENT ON COLUMN "TAPOSITIONAUTHRITY"."CREATEUSER" IS '������';
COMMENT ON COLUMN "TAPOSITIONAUTHRITY"."EFFECTTIME" IS '��Чʱ��';
COMMENT ON COLUMN "TAPOSITIONAUTHRITY"."MENUID" IS '�˵�Id';
COMMENT ON COLUMN "TAPOSITIONAUTHRITY"."POSITIONID" IS '��λid';
COMMENT ON COLUMN "TAPOSITIONAUTHRITY"."REAUTHRITY" IS '��Ȩ������ȨȨ��';
COMMENT ON COLUMN "TAPOSITIONAUTHRITY"."REPERMISSION" IS '��Ȩ����ʹ��Ȩ��';
COMMENT ON COLUMN "TAPOSITIONAUTHRITY"."USEPERMISSION" IS 'ʹ��Ȩ��';


CREATE TABLE "TARUNQIANPRINTSETUP"
(
"SETUPID" VARCHAR2(200) NOT NULL,
"SETUPVALUE" VARCHAR2(400) NOT NULL,
CONSTRAINT "PK_PRINTSETUP" NOT CLUSTER PRIMARY KEY("SETUPID")) STORAGE(ON "MAIN", CLUSTERBTR) ;
COMMENT ON TABLE "TARUNQIANPRINTSETUP" IS '��ӡ������Ϣ��';
COMMENT ON COLUMN "TARUNQIANPRINTSETUP"."SETUPID" IS '��ӡ���ñ�ţ�SetupId��';
COMMENT ON COLUMN "TARUNQIANPRINTSETUP"."SETUPVALUE" IS '��ӡ������Ϣ��SetupValue��';


CREATE TABLE "TARUNQIANRESOURCE"
(
"RAQFILENAME" VARCHAR2(200) NOT NULL,
"PARENTRAQFILENAME" VARCHAR2(200),
"RAQNAME" VARCHAR2(200),
"RAQTYPE" VARCHAR2(6),
"RAQFILE" BLOB,
"UPLOADOR" VARCHAR2(19),
"UPLOADTIME" TIMESTAMP(0),
"SUBROW" NUMBER,
"SUBCELL" NUMBER,
"RAQDATASOURCE" VARCHAR2(19),
"RAQPARAM" VARCHAR2(500),
"ORGID" VARCHAR2(15),
CONSTRAINT "PK_YHCIP_RUNQIAN_RESOURCE" NOT CLUSTER PRIMARY KEY("RAQFILENAME"),
CONSTRAINT "FK_YHCIP_RU_REFERENCE_YHCIP_RU" FOREIGN KEY("PARENTRAQFILENAME") REFERENCES "TARUNQIANRESOURCE"("RAQFILENAME") WITH INDEX ) STORAGE(ON "MAIN", CLUSTERBTR) ;
COMMENT ON TABLE "TARUNQIANRESOURCE" IS '��Ǭ����ģ��';
COMMENT ON COLUMN "TARUNQIANRESOURCE"."ORGID" IS '���ű��(OrgId)';
COMMENT ON COLUMN "TARUNQIANRESOURCE"."PARENTRAQFILENAME" IS '�������ʶ��ParentRaqfileName��';
COMMENT ON COLUMN "TARUNQIANRESOURCE"."RAQDATASOURCE" IS '����Դ��RaqDataSource��';
COMMENT ON COLUMN "TARUNQIANRESOURCE"."RAQFILE" IS '��Դ�ļ���RaqFile��';
COMMENT ON COLUMN "TARUNQIANRESOURCE"."RAQFILENAME" IS '�ļ���/�����ʶ��RaqfileName��';
COMMENT ON COLUMN "TARUNQIANRESOURCE"."RAQNAME" IS '�������ƣ�RaqName��';
COMMENT ON COLUMN "TARUNQIANRESOURCE"."RAQPARAM" IS '�������JSON��ʽStr��RaqParam��';
COMMENT ON COLUMN "TARUNQIANRESOURCE"."RAQTYPE" IS '�������ͣ�RaqType��';
COMMENT ON COLUMN "TARUNQIANRESOURCE"."SUBCELL" IS '������λ���У�SubCell��';
COMMENT ON COLUMN "TARUNQIANRESOURCE"."SUBROW" IS '������λ���У�SubRow��';
COMMENT ON COLUMN "TARUNQIANRESOURCE"."UPLOADOR" IS '�ϴ��ˣ�Uploador��';
COMMENT ON COLUMN "TARUNQIANRESOURCE"."UPLOADTIME" IS '�ϴ�ʱ�䣨UploadTime��';

CREATE TABLE "TARUNQIANAD52REFERENCE"
(
"MENUID" NUMBER(10,0),
"RAQFILENAME" VARCHAR2(200),
"LIMITED" NUMBER,
"SCALEEXP" NUMBER,
"ISGROUP" VARCHAR2(6),
"NEEDSAVEASEXCEL" VARCHAR2(6),
"NEEDSAVEASEXCEL2007" VARCHAR2(6),
"NEEDSAVEASPDF" VARCHAR2(6),
"NEEDSAVEASWORD" VARCHAR2(6),
"NEEDSAVEASTEXT" VARCHAR2(6),
"NEEDPRINT" VARCHAR2(6),
"ID" NUMBER(10,0) NOT NULL,
CONSTRAINT "PK_REPORT_INFO" NOT CLUSTER PRIMARY KEY("ID"),
CONSTRAINT "FK_REPORT_INFO" FOREIGN KEY("RAQFILENAME") REFERENCES "TARUNQIANRESOURCE"("RAQFILENAME")) STORAGE(ON "MAIN", CLUSTERBTR) ;
COMMENT ON TABLE "TARUNQIANAD52REFERENCE" IS 'YHCIP_RUNQIAN_AD52_REFERENCE��Ǭ����˵���Ϣ';
COMMENT ON COLUMN "TARUNQIANAD52REFERENCE"."ID" IS '����ID';
COMMENT ON COLUMN "TARUNQIANAD52REFERENCE"."ISGROUP" IS '�Ƿ��з�ҳ��IsGroup��';
COMMENT ON COLUMN "TARUNQIANAD52REFERENCE"."LIMITED" IS 'ÿҳ��ʾ����Limited��';
COMMENT ON COLUMN "TARUNQIANAD52REFERENCE"."MENUID" IS '���ܱ��';
COMMENT ON COLUMN "TARUNQIANAD52REFERENCE"."NEEDPRINT" IS '�Ƿ񱣴�ΪPrint��NeedPrint��';
COMMENT ON COLUMN "TARUNQIANAD52REFERENCE"."NEEDSAVEASEXCEL" IS '�Ƿ񱣴�ΪExcel��NeedSaveAsExcel��';
COMMENT ON COLUMN "TARUNQIANAD52REFERENCE"."NEEDSAVEASEXCEL2007" IS '�Ƿ񱣴�ΪExcel2007��NeedSaveAsExcel2007��';
COMMENT ON COLUMN "TARUNQIANAD52REFERENCE"."NEEDSAVEASPDF" IS '�Ƿ񱣴�ΪPdf��NeedSaveAsPdf��';
COMMENT ON COLUMN "TARUNQIANAD52REFERENCE"."NEEDSAVEASTEXT" IS '�Ƿ񱣴�ΪText��NeedSaveAsText��';
COMMENT ON COLUMN "TARUNQIANAD52REFERENCE"."NEEDSAVEASWORD" IS '�Ƿ񱣴�ΪWord��NeedSaveAsWord��';
COMMENT ON COLUMN "TARUNQIANAD52REFERENCE"."RAQFILENAME" IS '�ļ���/�����ʶ��RaqfileName��';
COMMENT ON COLUMN "TARUNQIANAD52REFERENCE"."SCALEEXP" IS 'JSP�����ű��ʣ�ScaleExp��';

CREATE TABLE "TASERVEREXCEPTIONLOG"
(
"ID" VARCHAR2(50) NOT NULL,
"IPADDRESS" VARCHAR2(255),
"TYPE" VARCHAR2(255),
"CONTENT" BLOB,
"TIME" TIMESTAMP(0),
"SYSPATH" VARCHAR2(50),
"CLIENTIP" VARCHAR2(50),
"URL" VARCHAR2(100),
"MENUID" VARCHAR2(8),
"MENUNAME" VARCHAR2(30),
"USERAGENT" VARCHAR2(200),
"EXCEPTIONTYPE" VARCHAR2(2),
"PARAMETER" BLOB,
"PORT" VARCHAR2(10)) STORAGE(ON "MAIN", CLUSTERBTR) ;
COMMENT ON TABLE "TASERVEREXCEPTIONLOG" IS 'ϵͳ�쳣��־��';
COMMENT ON COLUMN "TASERVEREXCEPTIONLOG"."CLIENTIP" IS '�ͻ���ip';
COMMENT ON COLUMN "TASERVEREXCEPTIONLOG"."CONTENT" IS '�쳣����';
COMMENT ON COLUMN "TASERVEREXCEPTIONLOG"."EXCEPTIONTYPE" IS '�쳣����(1 ϵͳ�쳣  2ҵ���쳣)';
COMMENT ON COLUMN "TASERVEREXCEPTIONLOG"."ID" IS 'id';
COMMENT ON COLUMN "TASERVEREXCEPTIONLOG"."IPADDRESS" IS '������ip��ַ';
COMMENT ON COLUMN "TASERVEREXCEPTIONLOG"."MENUID" IS '�˵�id';
COMMENT ON COLUMN "TASERVEREXCEPTIONLOG"."MENUNAME" IS '�˵�����';
COMMENT ON COLUMN "TASERVEREXCEPTIONLOG"."PARAMETER" IS '�������';
COMMENT ON COLUMN "TASERVEREXCEPTIONLOG"."SYSPATH" IS 'ϵͳ��ʶ';
COMMENT ON COLUMN "TASERVEREXCEPTIONLOG"."TIME" IS '����ʱ��';
COMMENT ON COLUMN "TASERVEREXCEPTIONLOG"."TYPE" IS '�쳣����';
COMMENT ON COLUMN "TASERVEREXCEPTIONLOG"."URL" IS '���ʹ���url';
COMMENT ON COLUMN "TASERVEREXCEPTIONLOG"."USERAGENT" IS '�ͻ��˻���';


CREATE TABLE "TASHAREPOSITION"
(
"SPOSITIONID" NUMBER(10,0),
"DPOSITIONID" NUMBER(10,0)) STORAGE(ON "MAIN", CLUSTERBTR) ;
COMMENT ON TABLE "TASHAREPOSITION" IS '�����λ��';
COMMENT ON COLUMN "TASHAREPOSITION"."DPOSITIONID" IS '���Ƹ�λid';
COMMENT ON COLUMN "TASHAREPOSITION"."SPOSITIONID" IS 'Դ��λid';


CREATE TABLE "TAUSER"
(
"USERID" NUMBER(10,0) NOT NULL,
"NAME" VARCHAR2(60) NOT NULL,
"SEX" CHAR(1),
"LOGINID" VARCHAR2(20) NOT NULL,
"PASSWORD" VARCHAR2(50) NOT NULL,
"PASSWORDFAULTNUM" NUMBER,
"PWDLASTMODIFYDATE" TIMESTAMP(0),
"ISLOCK" CHAR(1),
"SORT" NUMBER,
"EFFECTIVE" CHAR(1) NOT NULL,
"TEL" VARCHAR2(15),
"CREATEUSER" NUMBER(10,0),
"CREATETIME" TIMESTAMP(0) NOT NULL,
"DIRECTORGID" NUMBER(10,0) NOT NULL,
"DESTORY" CHAR(1),
"TYPEFLAG" NUMBER(10,0),
"AUTHMODE" VARCHAR2(2),
CONSTRAINT "PK_TAUSER" NOT CLUSTER PRIMARY KEY("USERID")) STORAGE(ON "MAIN", CLUSTERBTR) ;
COMMENT ON TABLE "TAUSER" IS '��Ա';
COMMENT ON COLUMN "TAUSER"."CREATETIME" IS '����ʱ��';
COMMENT ON COLUMN "TAUSER"."CREATEUSER" IS '������';
COMMENT ON COLUMN "TAUSER"."DESTORY" IS '�Ƿ�����';
COMMENT ON COLUMN "TAUSER"."DIRECTORGID" IS 'ֱ����֯';
COMMENT ON COLUMN "TAUSER"."EFFECTIVE" IS '��Ч��־';
COMMENT ON COLUMN "TAUSER"."ISLOCK" IS '������־';
COMMENT ON COLUMN "TAUSER"."LOGINID" IS '��½�˺�';
COMMENT ON COLUMN "TAUSER"."NAME" IS '����';
COMMENT ON COLUMN "TAUSER"."PASSWORD" IS '����';
COMMENT ON COLUMN "TAUSER"."PASSWORDFAULTNUM" IS '����������';
COMMENT ON COLUMN "TAUSER"."PWDLASTMODIFYDATE" IS '��������޸�ʱ��';
COMMENT ON COLUMN "TAUSER"."SEX" IS '�Ա�';
COMMENT ON COLUMN "TAUSER"."SORT" IS '�����';
COMMENT ON COLUMN "TAUSER"."TEL" IS '��ϵ�绰';
COMMENT ON COLUMN "TAUSER"."TYPEFLAG" IS '���ʶ';
COMMENT ON COLUMN "TAUSER"."USERID" IS '��Աid';


CREATE TABLE "TAUSERPOSITION"
(
"USERID" NUMBER(10,0) NOT NULL,
"POSITIONID" NUMBER(10,0) NOT NULL,
"MAINPOSITION" CHAR(1) NOT NULL,
"CREATEUSER" NUMBER(10,0) NOT NULL,
"CREATETIME" TIMESTAMP(0) NOT NULL,
CONSTRAINT "PK_TAUSERPOSITION" NOT CLUSTER PRIMARY KEY("USERID", "POSITIONID"),
CONSTRAINT "FK_RELATIONSHIP_9" FOREIGN KEY("USERID") REFERENCES "TAUSER"("USERID"),
CONSTRAINT "FK_RELATIONSHIP_10" FOREIGN KEY("POSITIONID") REFERENCES "TAPOSITION"("POSITIONID")) STORAGE(ON "MAIN", CLUSTERBTR) ;
COMMENT ON TABLE "TAUSERPOSITION" IS '��Ա��λ��ϵ��';
COMMENT ON COLUMN "TAUSERPOSITION"."CREATETIME" IS '����ʱ��';
COMMENT ON COLUMN "TAUSERPOSITION"."CREATEUSER" IS '������';
COMMENT ON COLUMN "TAUSERPOSITION"."MAINPOSITION" IS 'Ĭ�ϸ�λ';
COMMENT ON COLUMN "TAUSERPOSITION"."POSITIONID" IS '��λid';
COMMENT ON COLUMN "TAUSERPOSITION"."USERID" IS '��Աid';


CREATE TABLE "TAYAB003LEVELMG"
(
"PYAB003" VARCHAR2(6),
"YAB003" VARCHAR2(6)) STORAGE(ON "MAIN", CLUSTERBTR) ;
COMMENT ON TABLE "TAYAB003LEVELMG" IS '��������㼶��ϵ����';
COMMENT ON COLUMN "TAYAB003LEVELMG"."PYAB003" IS '���������';
COMMENT ON COLUMN "TAYAB003LEVELMG"."YAB003" IS '�������';


CREATE TABLE "TAYAB003SCOPE"
(
"YAB003" VARCHAR2(6) NOT NULL,
"YAB139" VARCHAR2(6) NOT NULL,
CONSTRAINT "PK_TAYAB003SCOPE" NOT CLUSTER PRIMARY KEY("YAB003", "YAB139")) STORAGE(ON "MAIN", CLUSTERBTR) ;
COMMENT ON TABLE "TAYAB003SCOPE" IS '����������Ȩ�޷�Χ��';
COMMENT ON COLUMN "TAYAB003SCOPE"."YAB003" IS '������';
COMMENT ON COLUMN "TAYAB003SCOPE"."YAB139" IS '����������Ȩ��';


CREATE TABLE "TAYAB139MG"
(
"YAB003" VARCHAR2(6),
"YAB139" VARCHAR2(20)) STORAGE(ON "MAIN", CLUSTERBTR) ;
COMMENT ON TABLE "TAYAB139MG" IS '�������������������Χ';
COMMENT ON COLUMN "TAYAB139MG"."YAB003" IS '�������';
COMMENT ON COLUMN "TAYAB139MG"."YAB139" IS '������';


CREATE TABLE "TAZKADDRESSMG"
(
"ZKID" VARCHAR2(20) NOT NULL,
"ZKADDRESS" VARCHAR2(200),
"APPNAME" VARCHAR2(60),
"APPNAMESPACE" VARCHAR2(30),
CONSTRAINT "PK_ZKID" NOT CLUSTER PRIMARY KEY("ZKID")) STORAGE(ON "MAIN", CLUSTERBTR) ;

CREATE TABLE "TEMPLATEMANAGER"
(
"TEMPLATEID" VARCHAR2(50) NOT NULL,
"TEMPLATENAME" VARCHAR2(50) NOT NULL,
"TEMPLATECONTENT" BLOB,
"TEMPLATETYPE" VARCHAR2(10),
"CREATEPEOPLE" NUMBER(10,0),
"CREATETIME" TIMESTAMP(0),
"EFFECTIVE" CHAR(1),
"CONTENT" VARCHAR2(20)) STORAGE(ON "MAIN", CLUSTERBTR) ;

CREATE TABLE "YHCIP_ORACLE_JOBS"
(
"JOBID" VARCHAR2(20) NOT NULL,
"ORACLEJOBID" VARCHAR2(20) NOT NULL,
"JOBNAME" VARCHAR2(100) NOT NULL,
"USERID" VARCHAR2(20) NOT NULL,
"WHAT" VARCHAR2(3900) NOT NULL,
"STARTTIME" VARCHAR2(200) NOT NULL,
"ENDTIME" TIMESTAMP(0),
"INTERVAL" VARCHAR2(200),
"SUBMITTIME" TIMESTAMP(0),
CONSTRAINT "PK_YHCIP_ORACLE_JOBS" NOT CLUSTER PRIMARY KEY("JOBID")) STORAGE(ON "MAIN", CLUSTERBTR) ;
COMMENT ON TABLE "YHCIP_ORACLE_JOBS" IS 'oracle��ʱ';
COMMENT ON COLUMN "YHCIP_ORACLE_JOBS"."ENDTIME" IS '����ʱ��';
COMMENT ON COLUMN "YHCIP_ORACLE_JOBS"."INTERVAL" IS 'ʱ����';
COMMENT ON COLUMN "YHCIP_ORACLE_JOBS"."JOBID" IS '����id';
COMMENT ON COLUMN "YHCIP_ORACLE_JOBS"."JOBNAME" IS '��������';
COMMENT ON COLUMN "YHCIP_ORACLE_JOBS"."ORACLEJOBID" IS 'oracle��jobid';
COMMENT ON COLUMN "YHCIP_ORACLE_JOBS"."STARTTIME" IS '��ʼʱ��';
COMMENT ON COLUMN "YHCIP_ORACLE_JOBS"."SUBMITTIME" IS '�ύʱ��';
COMMENT ON COLUMN "YHCIP_ORACLE_JOBS"."USERID" IS '�û�id';
COMMENT ON COLUMN "YHCIP_ORACLE_JOBS"."WHAT" IS 'ִ�еĹ���';


CREATE VIEW "AA10A1" ("AAA100","AAA101","AAA102","AAA103","YAB003","AAE120","VER")  
AS 
select
   AAA100,
   AAA101,
   AAA102,
   AAA103,
   YAB003,
   AAE120,
   VER
from
   AA10
;

CREATE VIEW "V_TALOGINLOG" ("LOGID","USERID","USERNAME","LOGINTIME","CLIENTIP","SESSIONID","SYSPATH","SERVERIP","CLIENTSYSTEM","CLIENTBROWSER","CLIENTSCREENSIZE")  
AS 
SELECT
  a.logid,
  a.userid,
  (SELECT name FROM tauser where userid = a.userid) as username,
  a.logintime,
  a.clientip,
  a.sessionid,
  a.syspath,
  a.serverip,
  NVL(a.clientsystem,'UNKNOW') as clientsystem,
  NVL(a.clientbrowser,'UNKNOW') as clientbrowser,
  NVL(a.clientscreensize,'UNKNOW') as clientscreensize
FROM TAONLINELOG a
Union all
SELECT
  a.logid,
  a.userid,
  (SELECT name FROM tauser where userid = a.userid) as username,
  a.logintime,
  a.clientip,
  a.sessionid,
  a.syspath,
  a.serverip,
  NVL(a.clientsystem,'UNKNOW') as clientsystem,
  NVL(a.clientbrowser,'UNKNOW') as clientbrowser,
  NVL(a.clientscreensize,'UNKNOW') as clientscreensize
FROM TALOGINHISTORYLOG a
;

CREATE VIEW "V_YAB139" ("USERID","MENUID","YAB139","SYSPATH")  
AS 
SELECT
       U.USERID AS USERID,
       M.MENUID AS MENUID,
       DAD.DIMENSIONPERMISSIONID AS YAB139,
       DAD.SYSPATH AS SYSPATH
FROM
       TAMENU M ,
       TADATAACCESSDIMENSION DAD,
       TAUSER U,
       TAPOSITION P,
       TAUSERPOSITION UP
WHERE 1=1
      AND U.USERID=UP.USERID
      AND (U.DESTORY IS NULL OR U.DESTORY=0)
      AND U.EFFECTIVE=1
      AND UP.POSITIONID=P.POSITIONID
      AND P.EFFECTIVE=1
      AND (P.VALIDTIME IS NULL OR P.VALIDTIME>=sysdate)
      AND P.POSITIONID=DAD.POSITIONID
      AND DAD.MENUID=M.MENUID
      AND DAD.DIMENSIONTYPE='YAB139'
      AND DAD.ALLACCESS=0
UNION
SELECT
       U.USERID AS USERID,
       M.MENUID AS MENUID,
       A.AAA102 AS YAB139,
       DAD.SYSPATH AS SYSPATH
FROM
       TAMENU M ,
       TADATAACCESSDIMENSION DAD,
       TAUSER U,
       TAPOSITION P,
       TAUSERPOSITION UP,
       AA10A1 A
WHERE 1=1
      AND U.USERID=UP.USERID
      AND (U.DESTORY IS NULL OR U.DESTORY=0)
      AND U.EFFECTIVE=1
      AND UP.POSITIONID=P.POSITIONID
      AND P.EFFECTIVE=1
      AND (P.VALIDTIME IS NULL OR P.VALIDTIME>=sysdate)
      AND P.POSITIONID=DAD.POSITIONID
      AND DAD.MENUID=M.MENUID
      AND DAD.DIMENSIONTYPE='YAB139'
      AND DAD.ALLACCESS<>0
      AND A.AAA100='YAB139'
;

CREATE SEQUENCE "HIBERNATE_SEQUENCE" INCREMENT BY 1 START WITH 236290 MAXVALUE 9223372036854775807 MINVALUE 1 CACHE 20;

CREATE SEQUENCE "SEQ_DEFAULT" INCREMENT BY 1 START WITH 110001 MAXVALUE 9223372036854775807 MINVALUE 1 CACHE 20;

CREATE SEQUENCE "SEQ_MESSAGE" INCREMENT BY 1 START WITH 4122 MAXVALUE 9223372036854775807 MINVALUE 1 CACHE 10;

CREATE SEQUENCE "TEMPLATE_SEQUENCE" INCREMENT BY 1 START WITH 982 MAXVALUE 9223372036854775807 MINVALUE 1 CACHE 20;

CREATE PACKAGE "PKG_YHCIP"  AS
   /*---------------------------------------------------------------------------
   ||  ������� ��pkg_YHCIP
   ||  ҵ�񻷽� ��YHCIP
   ||  �����б� ��˽�й��̺���
   ||             --------------------------------------------------------------
   ||             ���ù��̺���
   ||             --------------------------------------------------------------
   ||
   ||  ����˵�� ��
   ||  ������� ��
   ||  �汾��� ��Ver 1.0
   ||  �� �� �� ��������                      ������� ��YYYY-MM-DD
   ||-------------------------------------------------------------------------*/

   /*-------------------------------------------------------------------------*/
   /* ����ȫ��������������                                                    */
   /*-------------------------------------------------------------------------*/

   /*-------------------------------------------------------------------------*/
   /* ����ȫ�ֳ�������                                                        */
   /*-------------------------------------------------------------------------*/
   gn_def_OK  CONSTANT VARCHAR2(12) := 'NOERROR'; -- �ɹ�
   gn_def_ERR CONSTANT VARCHAR2(12) := '9999'; -- ϵͳ����

   GN_DEF_YES CONSTANT VARCHAR2(12) := '��'; -- ��
   GN_DEF_NO  CONSTANT VARCHAR2(12) := '��'; -- ��

   gs_def_DatetimeFormat  CONSTANT VARCHAR2(21) := 'YYYY-MM-DD HH24:MI:SS';
   gs_def_DateFormat      CONSTANT VARCHAR2(10) := 'YYYY-MM-DD';
   gs_def_YearMonthFormat CONSTANT VARCHAR2(6) := 'YYYYMM';
   gs_def_YearFormat      CONSTANT VARCHAR2(4) := 'YYYY';
   gs_def_TimeFormat      CONSTANT VARCHAR2(10) := 'HH24:MI:SS';
   gs_def_NumberFormat    CONSTANT VARCHAR2(15) := '999999999999.99';
   gs_def_NOFormat        CONSTANT VARCHAR2(15) := '999999999999999';
   gs_def_NullDate        CONSTANT DATE := TO_DATE('1900-01-01',
                                                   gs_def_DateFormat);

   /*-------------------------------------------------------------------------*/
   /* ���ù��̺�������                                                        */
   /*-------------------------------------------------------------------------*/

   /*ģ��*/
   PROCEDURE prc_Template (
      prm_AppCode                         OUT      VARCHAR2          ,
      prm_ErrorMsg                        OUT      VARCHAR2          );


   PROCEDURE prc_oracleJob (
			      prm_jobid                          IN OUT VARCHAR2      ,--jobid�ⲿ��������������YHCIP_ORACLE_JOBS�����������ȥ����oracle���ɵ�jobid
			      prm_jobname			                   IN     VARCHAR2      ,--��������
			      prm_what                           IN     VARCHAR2      ,--ִ�й��̣���Ҫ��;���ֺŽ�β
			      prm_next_date                      IN     VARCHAR2      ,--ִ��ʱ��
			      prm_interval                       IN     VARCHAR2      ,--���ѭ��ʱ��
			      prm_userid                         IN     VARCHAR2      ,--�û�id
			      prm_AppCode                        OUT    VARCHAR2      ,
			      prm_ErrorMsg                       OUT    VARCHAR2      );
   PROCEDURE prc_oraclejobbroken(
			      prm_jobid                          IN     VARCHAR2      ,--jobid�ⲿ��������������YHCIP_ORACLE_JOBS�����������ȥ����oracle���ɵ�jobid
			      prm_broken                         IN     VARCHAR2      ,--�Ƿ���ͣ
			      prm_next_date                      IN     VARCHAR2      ,--�´�ִ��ʱ��
			      prm_AppCode                        OUT    VARCHAR2      ,
			      prm_ErrorMsg                       OUT    VARCHAR2      );
   PROCEDURE prc_oraclejobchange (
			      prm_jobid                          IN OUT VARCHAR2      ,--jobid�ⲿ��������������YHCIP_ORACLE_JOBS�����������ȥ����oracle���ɵ�jobid
            prm_jobname                        IN     VARCHAR2      ,--��������
            prm_what                           IN     VARCHAR2      ,--ִ�й��̣���Ҫ��;���ֺŽ�β
            prm_next_date                      IN     VARCHAR2      ,--ִ��ʱ��
            prm_interval                       IN     VARCHAR2      ,--���ѭ��ʱ��
            prm_userid                         IN     VARCHAR2      ,--�û�id
            prm_AppCode                        OUT    VARCHAR2      ,
            prm_ErrorMsg                       OUT    VARCHAR2      )  ;
   PROCEDURE prc_removeJob (
      prm_jobid                          IN       VARCHAR2          ,
      prm_AppCode                        OUT      VARCHAR2          ,
      prm_ErrorMsg                       OUT      VARCHAR2          ) ;

END pkg_YHCIP;


insert into AA10 (AAA100, AAA101, AAA102, AAA103, YAB003, AAE120, VER)
values ('MENUTYPE', '�˵�����', '0', 'ͨ�ò˵�', '9999', '0', 0);
insert into AA10 (AAA100, AAA101, AAA102, AAA103, YAB003, AAE120, VER)
values ('MENUTYPE', '�˵�����', '1', 'ϵͳ����˵�', '9999', '0', 0);
insert into AA10 (AAA100, AAA101, AAA102, AAA103, YAB003, AAE120, VER)
values ('MENUTYPE', '�˵�����', '2', 'ҵ���ܲ˵�', '9999', '0', 0);
insert into AA10 (AAA100, AAA101, AAA102, AAA103, YAB003, AAE120, VER)
values ('POSITIONTYPE', '��λ����', '1', '���и�λ', '9999', '0', 0);
insert into AA10 (AAA100, AAA101, AAA102, AAA103, YAB003, AAE120, VER)
values ('POSITIONTYPE', '��λ����', '2', '����ר����λ', '9999', '0', 0);
insert into AA10 (AAA100, AAA101, AAA102, AAA103, YAB003, AAE120, VER)
values ('POSITIONTYPE', '��λ����', '3', 'ί�ɸ�λ', '9999', '0', 0);
insert into AA10 (AAA100, AAA101, AAA102, AAA103, YAB003, AAE120, VER)
values ('SEX', '�Ա�', '1', '��', '9999', '0', 0);
insert into AA10 (AAA100, AAA101, AAA102, AAA103, YAB003, AAE120, VER)
values ('SEX', '�Ա�', '2', 'Ů', '9999', '0', 0);
insert into AA10 (AAA100, AAA101, AAA102, AAA103, YAB003, AAE120, VER)
values ('SEX', '�Ա�', '0', '��', '9999', '0', 0);
insert into AA10 (AAA100, AAA101, AAA102, AAA103, YAB003, AAE120, VER)
values ('ORGTYPE', '��֯����', '01', '����', '9999', '0', 0);
insert into AA10 (AAA100, AAA101, AAA102, AAA103, YAB003, AAE120, VER)
values ('ORGTYPE', '��֯����', '02', '����', '9999', '0', 0);
insert into AA10 (AAA100, AAA101, AAA102, AAA103, YAB003, AAE120, VER)
values ('ORGTYPE', '��֯����', '04', '��', '9999', '0', 0);
insert into AA10 (AAA100, AAA101, AAA102, AAA103, YAB003, AAE120, VER)
values ('EFFECTIVE', '��Ч��־', '1', '��Ч', '9999', '0', 0);
insert into AA10 (AAA100, AAA101, AAA102, AAA103, YAB003, AAE120, VER)
values ('EFFECTIVE', '��Ч��־', '0', '��Ч', '9999', '0', 0);
insert into AA10 (AAA100, AAA101, AAA102, AAA103, YAB003, AAE120, VER)
values ('YESORNO', '�Ƿ�', '1', '��', '9999', '0', 0);
insert into AA10 (AAA100, AAA101, AAA102, AAA103, YAB003, AAE120, VER)
values ('YESORNO', '�Ƿ�', '0', '��', '9999', '0', 0);
insert into AA10 (AAA100, AAA101, AAA102, AAA103, YAB003, AAE120, VER)
values ('POLICY', '��ȫ����', '1', 'Ҫ��֤Ҫ��ʾ', '9999', '0', 0);
insert into AA10 (AAA100, AAA101, AAA102, AAA103, YAB003, AAE120, VER)
values ('POLICY', '��ȫ����', '2', 'Ҫ��֤����ʾ', '9999', '0', 0);
insert into AA10 (AAA100, AAA101, AAA102, AAA103, YAB003, AAE120, VER)
values ('POLICY', '��ȫ����', '3', '����֤����ʾ', '9999', '0', 0);
insert into AA10 (AAA100, AAA101, AAA102, AAA103, YAB003, AAE120, VER)
values ('POLICY', '��ȫ����', '4', '����֤Ҫ��ʾ', '9999', '0', 0);
insert into AA10 (AAA100, AAA101, AAA102, AAA103, YAB003, AAE120, VER)
values ('OPTYPE', '��������', '01', '������֯', '9999', '0', 0);
insert into AA10 (AAA100, AAA101, AAA102, AAA103, YAB003, AAE120, VER)
values ('OPTYPE', '��������', '02', '�༭��֯', '9999', '0', 0);
insert into AA10 (AAA100, AAA101, AAA102, AAA103, YAB003, AAE120, VER)
values ('OPTYPE', '��������', '03', '������֯', '9999', '0', 0);
insert into AA10 (AAA100, AAA101, AAA102, AAA103, YAB003, AAE120, VER)
values ('OPTYPE', '��������', '04', '������Ա', '9999', '0', 0);
insert into AA10 (AAA100, AAA101, AAA102, AAA103, YAB003, AAE120, VER)
values ('OPTYPE', '��������', '05', '�༭��Ա', '9999', '0', 0);
insert into AA10 (AAA100, AAA101, AAA102, AAA103, YAB003, AAE120, VER)
values ('OPTYPE', '��������', '06', '������Ա', '9999', '0', 0);
insert into AA10 (AAA100, AAA101, AAA102, AAA103, YAB003, AAE120, VER)
values ('OPTYPE', '��������', '07', '��������', '9999', '0', 0);
insert into AA10 (AAA100, AAA101, AAA102, AAA103, YAB003, AAE120, VER)
values ('OPTYPE', '��������', '08', '�����λ����Ա', '9999', '0', 0);
insert into AA10 (AAA100, AAA101, AAA102, AAA103, YAB003, AAE120, VER)
values ('OPTYPE', '��������', '09', '��������λ����Ա', '9999', '0', 0);
insert into AA10 (AAA100, AAA101, AAA102, AAA103, YAB003, AAE120, VER)
values ('OPTYPE', '��������', '10', '������λ', '9999', '0', 0);
insert into AA10 (AAA100, AAA101, AAA102, AAA103, YAB003, AAE120, VER)
values ('OPTYPE', '��������', '11', '�༭��λ', '9999', '0', 0);
insert into AA10 (AAA100, AAA101, AAA102, AAA103, YAB003, AAE120, VER)
values ('OPTYPE', '��������', '12', '���ø�λ', '9999', '0', 0);
insert into AA10 (AAA100, AAA101, AAA102, AAA103, YAB003, AAE120, VER)
values ('OPTYPE', '��������', '13', '�����λʹ��Ȩ��', '9999', '0', 0);
insert into AA10 (AAA100, AAA101, AAA102, AAA103, YAB003, AAE120, VER)
values ('OPTYPE', '��������', '14', '���ո�λʹ��Ȩ��', '9999', '0', 0);
insert into AA10 (AAA100, AAA101, AAA102, AAA103, YAB003, AAE120, VER)
values ('OPTYPE', '��������', '15', '���ø�λ', '9999', '0', 0);
insert into AA10 (AAA100, AAA101, AAA102, AAA103, YAB003, AAE120, VER)
values ('OPTYPE', '��������', '16', '������Ա', '9999', '0', 0);
insert into AA10 (AAA100, AAA101, AAA102, AAA103, YAB003, AAE120, VER)
values ('OPTYPE', '��������', '17', '������֯', '9999', '0', 0);
insert into AA10 (AAA100, AAA101, AAA102, AAA103, YAB003, AAE120, VER)
values ('OPTYPE', '��������', '18', 'ɾ����֯', '9999', '0', 0);
insert into AA10 (AAA100, AAA101, AAA102, AAA103, YAB003, AAE120, VER)
values ('OPTYPE', '��������', '19', '�����λ��Ȩ����ʹ��Ȩ��', '9999', '0', 0);
insert into AA10 (AAA100, AAA101, AAA102, AAA103, YAB003, AAE120, VER)
values ('OPTYPE', '��������', '20', '���ո�λ��Ȩ����ʹ��Ȩ��', '9999', '0', 0);
insert into AA10 (AAA100, AAA101, AAA102, AAA103, YAB003, AAE120, VER)
values ('OPTYPE', '��������', '21', '�����λ��Ȩ������ȨȨ��', '9999', '0', 0);
insert into AA10 (AAA100, AAA101, AAA102, AAA103, YAB003, AAE120, VER)
values ('OPTYPE', '��������', '22', '���ո�λ��Ȩ������ȨȨ��', '9999', '0', 0);
insert into AA10 (AAA100, AAA101, AAA102, AAA103, YAB003, AAE120, VER)
values ('OPTYPE', '��������', '23', 'ɾ������Ա', '9999', '0', 0);
insert into AA10 (AAA100, AAA101, AAA102, AAA103, YAB003, AAE120, VER)
values ('OPTYPE', '��������', '24', '��������Ա', '9999', '0', 0);
insert into AA10 (AAA100, AAA101, AAA102, AAA103, YAB003, AAE120, VER)
values ('OPTYPE', '��������', '25', 'ɾ����λ', '9999', '0', 0);
insert into AA10 (AAA100, AAA101, AAA102, AAA103, YAB003, AAE120, VER)
values ('OPTYPE', '��������', '26', 'ɾ����Ա', '9999', '0', 0);
insert into AA10 (AAA100, AAA101, AAA102, AAA103, YAB003, AAE120, VER)
values ('OPOBJTYPE', '������������', '01', '��֯', '9999', '0', 0);
insert into AA10 (AAA100, AAA101, AAA102, AAA103, YAB003, AAE120, VER)
values ('OPOBJTYPE', '������������', '02', '��Ա', '9999', '0', 0);
insert into AA10 (AAA100, AAA101, AAA102, AAA103, YAB003, AAE120, VER)
values ('OPOBJTYPE', '������������', '03', '��λ', '9999', '0', 0);
insert into AA10 (AAA100, AAA101, AAA102, AAA103, YAB003, AAE120, VER)
values ('OPOBJTYPE', '������������', '04', 'Ȩ��', '9999', '0', 0);
insert into AA10 (AAA100, AAA101, AAA102, AAA103, YAB003, AAE120, VER)
values ('YAB003', '������', '9999', '9999', '9999', '0', 0);
insert into AA10 (AAA100, AAA101, AAA102, AAA103, YAB003, AAE120, VER)
values ('RAQTYPE', '��������', '0', '��������', '9999', '0', 0);
insert into AA10 (AAA100, AAA101, AAA102, AAA103, YAB003, AAE120, VER)
values ('RAQTYPE', '��������', '1', '������', '9999', '0', 0);
insert into AA10 (AAA100, AAA101, AAA102, AAA103, YAB003, AAE120, VER)
values ('RAQTYPE', '��������', '2', '�ӱ���', '9999', '0', 0);
insert into aa10 (AAA100, AAA101, AAA102, AAA103, YAB003, AAE120, VER)
values ('AUTHMODE', '��֤��ʽ����', '04', 'Key��', '9999', '0', 0);
insert into aa10 (AAA100, AAA101, AAA102, AAA103, YAB003, AAE120, VER)
values ('AUTHMODE', 'Ȩ����֤��ʽ', '03', '����ʶ��', '9999', '0', 0);
insert into aa10 (AAA100, AAA101, AAA102, AAA103, YAB003, AAE120, VER)
values ('AUTHMODE', 'Ȩ����֤��ʽ', '02', 'ָ��ʶ��', '9999', '0', 0);
insert into aa10 (AAA100, AAA101, AAA102, AAA103, YAB003, AAE120, VER)
values ('AUTHMODE', 'Ȩ����֤��ʽ', '01', '�û�������', '9999', '0', 0);
insert into AA10 (AAA100, AAA101, AAA102, AAA103, YAB003, AAE120, VER)
values ('LOGLEVEL', '��־�ȼ�', '0', 'OFF', '9999', '0', 0);
insert into AA10 (AAA100, AAA101, AAA102, AAA103, YAB003, AAE120, VER)
values ('LOGLEVEL', '��־�ȼ�', '1', 'FATAL', '9999', '0', 0);
insert into AA10 (AAA100, AAA101, AAA102, AAA103, YAB003, AAE120, VER)
values ('LOGLEVEL', '��־�ȼ�', '2', 'ERROR', '9999', '0', 0);
insert into AA10 (AAA100, AAA101, AAA102, AAA103, YAB003, AAE120, VER)
values ('LOGLEVEL', '��־�ȼ�', '3', 'WARN', '9999', '0', 0);
insert into AA10 (AAA100, AAA101, AAA102, AAA103, YAB003, AAE120, VER)
values ('LOGLEVEL', '��־�ȼ�', '4', 'INFO', '9999', '0', 0);
insert into AA10 (AAA100, AAA101, AAA102, AAA103, YAB003, AAE120, VER)
values ('LOGLEVEL', '��־�ȼ�', '5', 'DEBUG', '9999', '0', 0);
insert into AA10 (AAA100, AAA101, AAA102, AAA103, YAB003, AAE120, VER)
values ('LOGLEVEL', '��־�ȼ�', '6', 'TRACE', '9999', '0', 0);
insert into AA10 (AAA100, AAA101, AAA102, AAA103, YAB003, AAE120, VER)
values ('LOGLEVEL', '��־�ȼ�', '7', 'ALL', '9999', '0', 0);
INSERT INTO AA10 (AAA100, AAA101, AAA102, AAA103, YAB003, AAE120, VER) VALUES ('POSITIONCATEGORY', '��λ���', '01', 'ҵ���', '9999', '0', 0);
INSERT INTO AA10 (AAA100, AAA101, AAA102, AAA103, YAB003, AAE120, VER) VALUES ('POSITIONCATEGORY', '��λ���', '02', '���˸�', '9999', '0', 0);
INSERT INTO AA10 (AAA100, AAA101, AAA102, AAA103, YAB003, AAE120, VER) VALUES ('AUDITSTATE', '���״̬', '0', '�������', '9999', '0', 0);
INSERT INTO AA10 (AAA100, AAA101, AAA102, AAA103, YAB003, AAE120, VER) VALUES ('AUDITSTATE', '���״̬', '1', '�����', '9999', '0', 0);
INSERT INTO AA10 (AAA100, AAA101, AAA102, AAA103, YAB003, AAE120, VER) VALUES ('AUDITSTATE', '���״̬', '2', '���ͨ��', '9999', '0', 0);
INSERT INTO AA10 (AAA100, AAA101, AAA102, AAA103, YAB003, AAE120, VER) VALUES ('AUDITSTATE', '���״̬', '3', '���δͨ��', '9999', '0', 0);
INSERT INTO AA10 (AAA100, AAA101, AAA102, AAA103, YAB003, AAE120, VER) VALUES ('TEMPLATETYPE', 'ģ������', '1', 'wordģ��(.xml)', '9999', '0', 0);
INSERT INTO AA10 (AAA100, AAA101, AAA102, AAA103, YAB003, AAE120, VER) VALUES ('TEMPLATETYPE', 'ģ������', '2', 'excelģ��(.xls/.xlsx)', '9999', '0', 0);


INSERT INTO TACONFIGSYSPATH (SERIALID, ID, NAME, URL, PY, CURSYSTEM) values('1','sysmg','ϵͳ����','http://127.0.0.1:8080/ta3/','xtgl','0');

INSERT INTO TAMENU (MENUID, PMENUID, MENUNAME, URL, MENUIDPATH, MENUNAMEPATH, ICONSKIN, SELECTIMAGE, REPORTID, ACCESSTIMEEL, EFFECTIVE, SECURITYPOLICY, ISDISMULTIPOS, QUICKCODE, SORTNO, RESOURCETYPE, MENULEVEL, ISLEAF, MENUTYPE, ISCACHE, SYSPATH, USEYAB003, TYPEFLAG, ISAUDITE, CONSOLEMODULE, CUSTOMENCODING, ISFILEDSCONTROL)
VALUES (1, 0, '�������', NULL, '1', '�������', 'tree-organisation', NULL, NULL, NULL, '1', '1', '0', NULL, 0, '01', 1, '0', '0', NULL, 'sysmg', '1', 0, '0', '0', NULL, '1');
INSERT INTO TAMENU (MENUID, PMENUID, MENUNAME, URL, MENUIDPATH, MENUNAMEPATH, ICONSKIN, SELECTIMAGE, REPORTID, ACCESSTIMEEL, EFFECTIVE, SECURITYPOLICY, ISDISMULTIPOS, QUICKCODE, SORTNO, RESOURCETYPE, MENULEVEL, ISLEAF, MENUTYPE, ISCACHE, SYSPATH, USEYAB003, TYPEFLAG, ISAUDITE, CONSOLEMODULE, CUSTOMENCODING, ISFILEDSCONTROL)
VALUES (2, 1, 'Ȩ�޹���', NULL, '1/2', '�������/Ȩ�޹���', 'icon-004?#87bfe8', NULL, NULL, NULL, '1', '1', '1', NULL, 0, '01', 2, '0', '1', NULL, 'sysmg', '1', NULL, '0', '0', NULL, '1');
INSERT INTO TAMENU (MENUID, PMENUID, MENUNAME, URL, MENUIDPATH, MENUNAMEPATH, ICONSKIN, SELECTIMAGE, REPORTID, ACCESSTIMEEL, EFFECTIVE, SECURITYPOLICY, ISDISMULTIPOS, QUICKCODE, SORTNO, RESOURCETYPE, MENULEVEL, ISLEAF, MENUTYPE, ISCACHE, SYSPATH, USEYAB003, TYPEFLAG, ISAUDITE, CONSOLEMODULE, CUSTOMENCODING, ISFILEDSCONTROL)
VALUES (3, 1, '��������', NULL, '1/3', '�������/��������', 'icon-001?#6A6A6A', NULL, NULL, NULL, '1', '1', '1', NULL, 1, '01', 2, '0', '1', NULL, 'sysmg', '1', NULL, '0', '0', NULL, '1');
INSERT INTO TAMENU (MENUID, PMENUID, MENUNAME, URL, MENUIDPATH, MENUNAMEPATH, ICONSKIN, SELECTIMAGE, REPORTID, ACCESSTIMEEL, EFFECTIVE, SECURITYPOLICY, ISDISMULTIPOS, QUICKCODE, SORTNO, RESOURCETYPE, MENULEVEL, ISLEAF, MENUTYPE, ISCACHE, SYSPATH, USEYAB003, TYPEFLAG, ISAUDITE, CONSOLEMODULE, CUSTOMENCODING, ISFILEDSCONTROL)
VALUES (4, 1, 'ϵͳ����', NULL, '1/4', '�������/ϵͳ����', 'icon-005?#E1785A', NULL, NULL, NULL, '1', '1', '0', NULL, 2, '01', 2, '0', '1', NULL, 'sysmg', NULL, 0, '0', '0', NULL, '1');
INSERT INTO TAMENU (MENUID, PMENUID, MENUNAME, URL, MENUIDPATH, MENUNAMEPATH, ICONSKIN, SELECTIMAGE, REPORTID, ACCESSTIMEEL, EFFECTIVE, SECURITYPOLICY, ISDISMULTIPOS, QUICKCODE, SORTNO, RESOURCETYPE, MENULEVEL, ISLEAF, MENUTYPE, ISCACHE, SYSPATH, USEYAB003, TYPEFLAG, ISAUDITE, CONSOLEMODULE, CUSTOMENCODING, ISFILEDSCONTROL)
VALUES (5, 1, '����̨ʾ��', NULL, '1/5', '�������/����̨ʾ��', 'icon-010?#E7B346', NULL, NULL, NULL, '1', '2', '1', NULL, 3, '01', 2, '0', '2', NULL, 'sysmg', '1', NULL, '0', '0', NULL, '1');
INSERT INTO TAMENU (MENUID, PMENUID, MENUNAME, URL, MENUIDPATH, MENUNAMEPATH, ICONSKIN, SELECTIMAGE, REPORTID, ACCESSTIMEEL, EFFECTIVE, SECURITYPOLICY, ISDISMULTIPOS, QUICKCODE, SORTNO, RESOURCETYPE, MENULEVEL, ISLEAF, MENUTYPE, ISCACHE, SYSPATH, USEYAB003, TYPEFLAG, ISAUDITE, CONSOLEMODULE, CUSTOMENCODING, ISFILEDSCONTROL)
VALUES (6, 2, '��֯��Ա����', 'org/orgUserMgAction.do', '1/2/6', '�������/Ȩ�޹���/��֯��Ա����', 'icon-029?#88BBF1', NULL, NULL, NULL, '1', '1', '1', NULL, 0, '01', 3, '1', '1', NULL, 'sysmg', '1', NULL, '0', '0', NULL, '1');
INSERT INTO TAMENU (MENUID, PMENUID, MENUNAME, URL, MENUIDPATH, MENUNAMEPATH, ICONSKIN, SELECTIMAGE, REPORTID, ACCESSTIMEEL, EFFECTIVE, SECURITYPOLICY, ISDISMULTIPOS, QUICKCODE, SORTNO, RESOURCETYPE, MENULEVEL, ISLEAF, MENUTYPE, ISCACHE, SYSPATH, USEYAB003, TYPEFLAG, ISAUDITE, CONSOLEMODULE, CUSTOMENCODING, ISFILEDSCONTROL)
VALUES (7, 2, '����ԱȨ�޹���', 'org/admin/adminUserMgAction.do', '1/2/7', '�������/Ȩ�޹���/����ԱȨ�޹���', 'icon-011?#33475F', NULL, NULL, NULL, '1', '1', '1', NULL, 1, '01', 3, '1', '1', NULL, 'sysmg', '1', NULL, '0', '0', NULL, '1');
INSERT INTO TAMENU (MENUID, PMENUID, MENUNAME, URL, MENUIDPATH, MENUNAMEPATH, ICONSKIN, SELECTIMAGE, REPORTID, ACCESSTIMEEL, EFFECTIVE, SECURITYPOLICY, ISDISMULTIPOS, QUICKCODE, SORTNO, RESOURCETYPE, MENULEVEL, ISLEAF, MENUTYPE, ISCACHE, SYSPATH, USEYAB003, TYPEFLAG, ISAUDITE, CONSOLEMODULE, CUSTOMENCODING, ISFILEDSCONTROL)
VALUES (8, 2, '�����û�Ȩ�޹���', 'org/position/positionUserMgAction.do', '1/2/8', '�������/Ȩ�޹���/�����û�Ȩ�޹���', 'icon-023?#B59BC9', NULL, NULL, NULL, '1', '1', '1', NULL, 2, '01', 3, '1', '1', NULL, 'sysmg', '1', NULL, '0', '0', NULL, '1');
INSERT INTO TAMENU (MENUID, PMENUID, MENUNAME, URL, MENUIDPATH, MENUNAMEPATH, ICONSKIN, SELECTIMAGE, REPORTID, ACCESSTIMEEL, EFFECTIVE, SECURITYPOLICY, ISDISMULTIPOS, QUICKCODE, SORTNO, RESOURCETYPE, MENULEVEL, ISLEAF, MENUTYPE, ISCACHE, SYSPATH, USEYAB003, TYPEFLAG, ISAUDITE, CONSOLEMODULE, CUSTOMENCODING, ISFILEDSCONTROL)
VALUES (9, 2, '����Ȩ����Ȩ', 'org/position/similarAuthorityAction.do', '1/2/9', '�������/Ȩ�޹���/����Ȩ����Ȩ', 'icon-014?#936BB2', NULL, NULL, NULL, '1', '1', '1', NULL, 3, '01', 3, '1', '1', NULL, 'sysmg', '1', NULL, '0', '0', NULL, '1');
INSERT INTO TAMENU (MENUID, PMENUID, MENUNAME, URL, MENUIDPATH, MENUNAMEPATH, ICONSKIN, SELECTIMAGE, REPORTID, ACCESSTIMEEL, EFFECTIVE, SECURITYPOLICY, ISDISMULTIPOS, QUICKCODE, SORTNO, RESOURCETYPE, MENULEVEL, ISLEAF, MENUTYPE, ISCACHE, SYSPATH, USEYAB003, TYPEFLAG, ISAUDITE, CONSOLEMODULE, CUSTOMENCODING, ISFILEDSCONTROL)
VALUES (10, 2, '����Ȩ�޴���', 'org/position/delegatePositionAction.do', '1/2/10', '�������/Ȩ�޹���/����Ȩ�޴���', 'icon-057?#56ABE4', NULL, NULL, NULL, '1', '1', '1', NULL, 4, '01', 3, '1', '1', NULL, 'sysmg', '1', NULL, '0', '0', NULL, '1');
INSERT INTO TAMENU (MENUID, PMENUID, MENUNAME, URL, MENUIDPATH, MENUNAMEPATH, ICONSKIN, SELECTIMAGE, REPORTID, ACCESSTIMEEL, EFFECTIVE, SECURITYPOLICY, ISDISMULTIPOS, QUICKCODE, SORTNO, RESOURCETYPE, MENULEVEL, ISLEAF, MENUTYPE, ISCACHE, SYSPATH, USEYAB003, TYPEFLAG, ISAUDITE, CONSOLEMODULE, CUSTOMENCODING, ISFILEDSCONTROL)
VALUES (11, 3, '�˵�����', 'sysapp/menuMgAction.do', '1/3/11', '�������/��������/�˵�����', 'icon-065?#E5937C', NULL, NULL, NULL, '1', '1', '1', NULL, 0, '01', 3, '1', '1', NULL, 'sysmg', '1', NULL, '0', '0', NULL, '1');
INSERT INTO TAMENU (MENUID, PMENUID, MENUNAME, URL, MENUIDPATH, MENUNAMEPATH, ICONSKIN, SELECTIMAGE, REPORTID, ACCESSTIMEEL, EFFECTIVE, SECURITYPOLICY, ISDISMULTIPOS, QUICKCODE, SORTNO, RESOURCETYPE, MENULEVEL, ISLEAF, MENUTYPE, ISCACHE, SYSPATH, USEYAB003, TYPEFLAG, ISAUDITE, CONSOLEMODULE, CUSTOMENCODING, ISFILEDSCONTROL)
VALUES (12, 3, '������', 'appCodeTable/appCodeMainController.do', '1/3/12', '�������/��������/������', 'icon-026?#B4D984', NULL, NULL, NULL, '1', '1', '1', NULL, 1, '01', 3, '1', '1', NULL, 'sysmg', '1', NULL, '0', '0', NULL, '1');
INSERT INTO TAMENU (MENUID, PMENUID, MENUNAME, URL, MENUIDPATH, MENUNAMEPATH, ICONSKIN, SELECTIMAGE, REPORTID, ACCESSTIMEEL, EFFECTIVE, SECURITYPOLICY, ISDISMULTIPOS, QUICKCODE, SORTNO, RESOURCETYPE, MENULEVEL, ISLEAF, MENUTYPE, ISCACHE, SYSPATH, USEYAB003, TYPEFLAG, ISAUDITE, CONSOLEMODULE, CUSTOMENCODING, ISFILEDSCONTROL)
VALUES (13, 3, '��Ⱥserver��ַ����', 'sysapp/serverAddressAction.do', '1/3/13', '�������/��������/��Ⱥserver��ַ����', 'icon-049?#56ABE4', NULL, NULL, NULL, '1', '1', '1', NULL, 2, '01', 3, '1', '1', NULL, 'sysmg', '1', NULL, '0', '0', NULL, '1');
INSERT INTO TAMENU (MENUID, PMENUID, MENUNAME, URL, MENUIDPATH, MENUNAMEPATH, ICONSKIN, SELECTIMAGE, REPORTID, ACCESSTIMEEL, EFFECTIVE, SECURITYPOLICY, ISDISMULTIPOS, QUICKCODE, SORTNO, RESOURCETYPE, MENULEVEL, ISLEAF, MENUTYPE, ISCACHE, SYSPATH, USEYAB003, TYPEFLAG, ISAUDITE, CONSOLEMODULE, CUSTOMENCODING, ISFILEDSCONTROL)
VALUES (14, 3, '����������֯��Ա', 'org/upload/uploadOrgUserAction.do', '1/3/14', '�������/��������/����������֯��Ա', 'icon-035?#97CC52', NULL, NULL, NULL, '1', '1', '1', NULL, 3, '01', 3, '1', '1', NULL, 'sysmg', '1', NULL, '0', '0', NULL, '1');
INSERT INTO TAMENU (MENUID, PMENUID, MENUNAME, URL, MENUIDPATH, MENUNAMEPATH, ICONSKIN, SELECTIMAGE, REPORTID, ACCESSTIMEEL, EFFECTIVE, SECURITYPOLICY, ISDISMULTIPOS, QUICKCODE, SORTNO, RESOURCETYPE, MENULEVEL, ISLEAF, MENUTYPE, ISCACHE, SYSPATH, USEYAB003, TYPEFLAG, ISAUDITE, CONSOLEMODULE, CUSTOMENCODING, ISFILEDSCONTROL)
VALUES (15, 4, 'oracle��ʱ����', 'scheduler/oracleJobAction.do', '1/4/15', '�������/ϵͳ����/oracle��ʱ����', 'icon-060?#00BB9C', NULL, NULL, NULL, '1', '1', '1', NULL, 0, '01', 3, '1', '1', NULL, 'sysmg', '1', NULL, '0', '0', NULL, '1');
INSERT INTO TAMENU (MENUID, PMENUID, MENUNAME, URL, MENUIDPATH, MENUNAMEPATH, ICONSKIN, SELECTIMAGE, REPORTID, ACCESSTIMEEL, EFFECTIVE, SECURITYPOLICY, ISDISMULTIPOS, QUICKCODE, SORTNO, RESOURCETYPE, MENULEVEL, ISLEAF, MENUTYPE, ISCACHE, SYSPATH, USEYAB003, TYPEFLAG, ISAUDITE, CONSOLEMODULE, CUSTOMENCODING, ISFILEDSCONTROL)
VALUES (16, 4, '��Ǭ�������', NULL, '1/4/16', '�������/ϵͳ����/��Ǭ�������', 'icon-053?#deaf49', NULL, NULL, NULL, '1', '1', '1', NULL, 1, '01', 3, '0', '1', NULL, 'sysmg', NULL, NULL, '0', '0', NULL, '1');
INSERT INTO TAMENU (MENUID, PMENUID, MENUNAME, URL, MENUIDPATH, MENUNAMEPATH, ICONSKIN, SELECTIMAGE, REPORTID, ACCESSTIMEEL, EFFECTIVE, SECURITYPOLICY, ISDISMULTIPOS, QUICKCODE, SORTNO, RESOURCETYPE, MENULEVEL, ISLEAF, MENUTYPE, ISCACHE, SYSPATH, USEYAB003, TYPEFLAG, ISAUDITE, CONSOLEMODULE, CUSTOMENCODING, ISFILEDSCONTROL)
VALUES (17, 4, 'ϵͳ·������', 'sysapp/configSysPathAction.do', '1/4/17', '�������/ϵͳ����/ϵͳ·������', 'icon-028?#B196C7', NULL, NULL, NULL, '1', '1', '1', NULL, 2, '01', 3, '1', '1', NULL, 'sysmg', '1', NULL, '0', '0', NULL, '1');
INSERT INTO TAMENU (MENUID, PMENUID, MENUNAME, URL, MENUIDPATH, MENUNAMEPATH, ICONSKIN, SELECTIMAGE, REPORTID, ACCESSTIMEEL, EFFECTIVE, SECURITYPOLICY, ISDISMULTIPOS, QUICKCODE, SORTNO, RESOURCETYPE, MENULEVEL, ISLEAF, MENUTYPE, ISCACHE, SYSPATH, USEYAB003, TYPEFLAG, ISAUDITE, CONSOLEMODULE, CUSTOMENCODING, ISFILEDSCONTROL)
VALUES (18, 4, 'ϵͳ�쳣��־', 'sysapp/syslogmg/serverExceptionLog/serverExceptionLogController.do', '1/4/18', '�������/ϵͳ����/ϵͳ�쳣��־', 'icon-067?#E1785A', NULL, NULL, NULL, '1', '1', '1', NULL, 3, '01', 3, '1', '1', NULL, 'sysmg', NULL, 0, '0', '0', NULL, '1');
INSERT INTO TAMENU (MENUID, PMENUID, MENUNAME, URL, MENUIDPATH, MENUNAMEPATH, ICONSKIN, SELECTIMAGE, REPORTID, ACCESSTIMEEL, EFFECTIVE, SECURITYPOLICY, ISDISMULTIPOS, QUICKCODE, SORTNO, RESOURCETYPE, MENULEVEL, ISLEAF, MENUTYPE, ISCACHE, SYSPATH, USEYAB003, TYPEFLAG, ISAUDITE, CONSOLEMODULE, CUSTOMENCODING, ISFILEDSCONTROL)
VALUES (19, 16, '��Ǭ����˵�����', 'runqian/queryReportMgAction.do', '1/2/16/19', '�������/ϵͳ����/��Ǭ�������/��Ǭ����˵�����', 'icon-065?#deaf49', NULL, NULL, NULL, '1', '1', '1', NULL, 1, '01', 4, '1', '1', NULL, 'sysmg', NULL, NULL, '0', '0', NULL, '1');
INSERT INTO TAMENU (MENUID, PMENUID, MENUNAME, URL, MENUIDPATH, MENUNAMEPATH, ICONSKIN, SELECTIMAGE, REPORTID, ACCESSTIMEEL, EFFECTIVE, SECURITYPOLICY, ISDISMULTIPOS, QUICKCODE, SORTNO, RESOURCETYPE, MENULEVEL, ISLEAF, MENUTYPE, ISCACHE, SYSPATH, USEYAB003, TYPEFLAG, ISAUDITE, CONSOLEMODULE, CUSTOMENCODING, ISFILEDSCONTROL)
VALUES (20, 16, '��Ǭ����ģ�����', 'runqian/runQianReportFileMgAction.do', '1/2/16/20', '�������/ϵͳ����/��Ǭ�������/��Ǭ����ģ�����', 'icon-037?#deaf49', NULL, NULL, NULL, '1', '1', '1', NULL, 0, '01', 4, '1', '1', NULL, 'sysmg', NULL, NULL, '0', '0', NULL, '1');
INSERT INTO TAMENU (MENUID, PMENUID, MENUNAME, URL, MENUIDPATH, MENUNAMEPATH, ICONSKIN, SELECTIMAGE, REPORTID, ACCESSTIMEEL, EFFECTIVE, SECURITYPOLICY, ISDISMULTIPOS, QUICKCODE, SORTNO, RESOURCETYPE, MENULEVEL, ISLEAF, MENUTYPE, ISCACHE, SYSPATH, USEYAB003, TYPEFLAG, ISAUDITE, CONSOLEMODULE, CUSTOMENCODING, ISFILEDSCONTROL)
VALUES (21, 5, '��������', 'indexSRC/worktable/console/daiban.html', '1/5/21', '�������/����̨ʾ��/��������', 'icon-006?#E1785A', NULL, NULL, NULL, '1', '3', '1', NULL, 0, '01', 3, '1', '2', NULL, 'sysmg', '1', NULL, '0', '1', NULL, '1');
INSERT INTO TAMENU (MENUID, PMENUID, MENUNAME, URL, MENUIDPATH, MENUNAMEPATH, ICONSKIN, SELECTIMAGE, REPORTID, ACCESSTIMEEL, EFFECTIVE, SECURITYPOLICY, ISDISMULTIPOS, QUICKCODE, SORTNO, RESOURCETYPE, MENULEVEL, ISLEAF, MENUTYPE, ISCACHE, SYSPATH, USEYAB003, TYPEFLAG, ISAUDITE, CONSOLEMODULE, CUSTOMENCODING, ISFILEDSCONTROL)
VALUES (22, 5, 'ϵͳ', 'indexSRC/worktable/console/system.html', '1/5/22', '�������/����̨ʾ��/ϵͳ', 'icon-005?#E1785A', NULL, NULL, NULL, '1', '3', '1', NULL, 1, '01', 3, '1', '2', NULL, 'sysmg', '1', NULL, '0', '1', NULL, '1');
INSERT INTO TAMENU (MENUID, PMENUID, MENUNAME, URL, MENUIDPATH, MENUNAMEPATH, ICONSKIN, SELECTIMAGE, REPORTID, ACCESSTIMEEL, EFFECTIVE, SECURITYPOLICY, ISDISMULTIPOS, QUICKCODE, SORTNO, RESOURCETYPE, MENULEVEL, ISLEAF, MENUTYPE, ISCACHE, SYSPATH, USEYAB003, TYPEFLAG, ISAUDITE, CONSOLEMODULE, CUSTOMENCODING, ISFILEDSCONTROL)
VALUES (23, 5, '֪ͨ', 'indexSRC/worktable/console/tongzhi.html', '1/5/23', '�������/����̨ʾ��/֪ͨ', 'icon-015?#97CC52', NULL, NULL, NULL, '1', '3', '1', NULL, 2, '01', 3, '1', '2', NULL, 'sysmg', '1', NULL, '0', '1', NULL, '1');
INSERT INTO TAMENU (MENUID, PMENUID, MENUNAME, URL, MENUIDPATH, MENUNAMEPATH, ICONSKIN, SELECTIMAGE, REPORTID, ACCESSTIMEEL, EFFECTIVE, SECURITYPOLICY, ISDISMULTIPOS, QUICKCODE, SORTNO, RESOURCETYPE, MENULEVEL, ISLEAF, MENUTYPE, ISCACHE, SYSPATH, USEYAB003, TYPEFLAG, ISAUDITE, CONSOLEMODULE, CUSTOMENCODING, ISFILEDSCONTROL)
VALUES (24, 5, 'Эͬ����', 'indexSRC/worktable/console/xietong.html', '1/5/24', '�������/����̨ʾ��/Эͬ����', 'icon-045?#33475F', NULL, NULL, NULL, '1', '3', '1', NULL, 3, '01', 3, '1', '2', NULL, 'sysmg', '1', NULL, '0', '1', NULL, '1');
INSERT INTO TAMENU (MENUID, PMENUID, MENUNAME, URL, MENUIDPATH, MENUNAMEPATH, ICONSKIN, SELECTIMAGE, REPORTID, ACCESSTIMEEL, EFFECTIVE, SECURITYPOLICY, ISDISMULTIPOS, QUICKCODE, SORTNO, RESOURCETYPE, MENULEVEL, ISLEAF, MENUTYPE, ISCACHE, SYSPATH, USEYAB003, TYPEFLAG, ISAUDITE, CONSOLEMODULE, CUSTOMENCODING, ISFILEDSCONTROL)
VALUES (25, 5, '������ͳ��', 'indexSRC/worktable/console/yewuliang.html', '1/5/25', '�������/����̨ʾ��/������ͳ��', 'icon-048?#42dbd4', NULL, NULL, NULL, '1', '3', '1', NULL, 4, '01', 3, '1', '2', NULL, 'sysmg', '1', NULL, '0', '1', NULL, '1');
INSERT INTO TAMENU (MENUID, PMENUID, MENUNAME, URL, MENUIDPATH, MENUNAMEPATH, ICONSKIN, SELECTIMAGE, REPORTID, ACCESSTIMEEL, EFFECTIVE, SECURITYPOLICY, ISDISMULTIPOS, QUICKCODE, SORTNO, RESOURCETYPE, MENULEVEL, ISLEAF, MENUTYPE, ISCACHE, SYSPATH, USEYAB003, TYPEFLAG, ISAUDITE, CONSOLEMODULE, CUSTOMENCODING, ISFILEDSCONTROL)
VALUES (26, 5, '�Ǳ���', 'indexSRC/worktable/console/yibiaopan.html', '1/5/26', '�������/����̨ʾ��/�Ǳ���', 'icon-008?#a397e8', NULL, NULL, NULL, '1', '3', '1', NULL, 5, '01', 3, '1', '2', NULL, 'sysmg', '1', NULL, '0', '1', NULL, '1');
INSERT INTO TAMENU (MENUID, PMENUID, MENUNAME, URL, MENUIDPATH, MENUNAMEPATH, ICONSKIN, SELECTIMAGE, REPORTID, ACCESSTIMEEL, EFFECTIVE, SECURITYPOLICY, ISDISMULTIPOS, QUICKCODE, SORTNO, RESOURCETYPE, MENULEVEL, ISLEAF, MENUTYPE, ISCACHE, SYSPATH, USEYAB003, TYPEFLAG, ISAUDITE, CONSOLEMODULE, CUSTOMENCODING, ISFILEDSCONTROL)
VALUES (27, 2, '�����������', 'org/agencies/agenciesMgAction.do', '1/2/27', '�������/Ȩ�޹���/�����������', 'icon-001?#6A6A6A', NULL, NULL, NULL, '1', '1', '1', NULL, 5, '01', 3, '1', '1', NULL, 'sysmg', '1', NULL, '0', '0', NULL, '1');
INSERT INTO TAMENU (MENUID, PMENUID, MENUNAME, URL, MENUIDPATH, MENUNAMEPATH, ICONSKIN, SELECTIMAGE, REPORTID, ACCESSTIMEEL, EFFECTIVE, SECURITYPOLICY, ISDISMULTIPOS, QUICKCODE, SORTNO, RESOURCETYPE, MENULEVEL, ISLEAF, MENUTYPE, ISCACHE, SYSPATH, USEYAB003, TYPEFLAG, ISAUDITE, CONSOLEMODULE, CUSTOMENCODING, ISFILEDSCONTROL)
VALUES (28, 2, '�ֶ���Ȩ', 'org/field/fieldAuthorMgAction.do', '1/2/28', '�������/Ȩ�޹���/�ֶ���Ȩ', 'icon-027?#00BB9C', NULL, NULL, NULL, '1', '1', '1', NULL, 6, '01', 3, '1', '1', NULL, 'sysmg', '1', NULL, '0', '0', NULL, '1');
INSERT INTO TAMENU (MENUID, PMENUID, MENUNAME, URL, MENUIDPATH, MENUNAMEPATH, ICONSKIN, SELECTIMAGE, REPORTID, ACCESSTIMEEL, EFFECTIVE, SECURITYPOLICY, ISDISMULTIPOS, QUICKCODE, SORTNO, RESOURCETYPE, MENULEVEL, ISLEAF, MENUTYPE, ISCACHE, SYSPATH, USEYAB003, TYPEFLAG, ISAUDITE, CONSOLEMODULE, CUSTOMENCODING, ISFILEDSCONTROL)
VALUES (29, 1, '֪ͨ����', NULL, '1/29', '�������/֪ͨ����', 'icon-017?#cf829d', NULL, NULL, NULL, '1', '1', '1', NULL, 4, '01', 2, '0', '2', NULL, 'sysmg', '1', NULL, '0', '0', NULL, '1');
INSERT INTO TAMENU (MENUID, PMENUID, MENUNAME, URL, MENUIDPATH, MENUNAMEPATH, ICONSKIN, SELECTIMAGE, REPORTID, ACCESSTIMEEL, EFFECTIVE, SECURITYPOLICY, ISDISMULTIPOS, QUICKCODE, SORTNO, RESOURCETYPE, MENULEVEL, ISLEAF, MENUTYPE, ISCACHE, SYSPATH, USEYAB003, TYPEFLAG, ISAUDITE, CONSOLEMODULE, CUSTOMENCODING, ISFILEDSCONTROL)
VALUES (30, 29, '֪ͨ����', 'message/messageSend.do', '1/29/30', '�������/֪ͨ����/֪ͨ����', 'icon-071?#e37de3', NULL, NULL, NULL, '1', '1', '1', NULL, 0, '01', 3, '1', '2', NULL, 'sysmg', '1', NULL, '0', '0', NULL, '1');
INSERT INTO TAMENU (MENUID, PMENUID, MENUNAME, URL, MENUIDPATH, MENUNAMEPATH, ICONSKIN, SELECTIMAGE, REPORTID, ACCESSTIMEEL, EFFECTIVE, SECURITYPOLICY, ISDISMULTIPOS, QUICKCODE, SORTNO, RESOURCETYPE, MENULEVEL, ISLEAF, MENUTYPE, ISCACHE, SYSPATH, USEYAB003, TYPEFLAG, ISAUDITE, CONSOLEMODULE, CUSTOMENCODING, ISFILEDSCONTROL)
VALUES (31, 29, '֪ͨ���', 'message/messageCheck.do', '1/29/31', '�������/֪ͨ����/֪ͨ���', 'icon-050?#27d971', NULL, NULL, NULL, '1', '1', '1', NULL, 1, '01', 3, '1', '2', NULL, 'sysmg', '1', NULL, '0', '0', NULL, '1');
INSERT INTO TAMENU (MENUID, PMENUID, MENUNAME, URL, MENUIDPATH, MENUNAMEPATH, ICONSKIN, SELECTIMAGE, REPORTID, ACCESSTIMEEL, EFFECTIVE, SECURITYPOLICY, ISDISMULTIPOS, QUICKCODE, SORTNO, RESOURCETYPE, MENULEVEL, ISLEAF, MENUTYPE, ISCACHE, SYSPATH, USEYAB003, TYPEFLAG, ISAUDITE, CONSOLEMODULE, CUSTOMENCODING, ISFILEDSCONTROL)
VALUES (32, 29, '֪ͨɾ��', 'message/messageDelete.do', '1/29/32', '�������/֪ͨ����/֪ͨɾ��', 'icon-039?#db4b89', NULL, NULL, NULL, '1', '1', '1', NULL, 2, '01', 3, '1', '2', NULL, 'sysmg', '1', NULL, '0', '0', NULL, '1');
INSERT INTO TAMENU (MENUID, PMENUID, MENUNAME, URL, MENUIDPATH, MENUNAMEPATH, ICONSKIN, SELECTIMAGE, REPORTID, ACCESSTIMEEL, EFFECTIVE, SECURITYPOLICY, ISDISMULTIPOS, QUICKCODE, SORTNO, RESOURCETYPE, MENULEVEL, ISLEAF, MENUTYPE, ISCACHE, SYSPATH, USEYAB003, TYPEFLAG, ISAUDITE, CONSOLEMODULE, CUSTOMENCODING, ISFILEDSCONTROL)
VALUES (33, 3, 'ģ�����', 'templateMg/templateMgController.do', '1/3/33', '�������/��������/ģ�����', 'icon-037?#8ABCF1', NULL, NULL, NULL, '1', '1', '1', NULL, 4, '01', 3, '1', '1', NULL, 'sysmg', '1', NULL, '0', '0', NULL, '1');
INSERT INTO TAMENU (MENUID, PMENUID, MENUNAME, URL, MENUIDPATH, MENUNAMEPATH, ICONSKIN, SELECTIMAGE, REPORTID, ACCESSTIMEEL, EFFECTIVE, SECURITYPOLICY, ISDISMULTIPOS, QUICKCODE, SORTNO, RESOURCETYPE, MENULEVEL, ISLEAF, MENUTYPE, ISCACHE, SYSPATH, USEYAB003, TYPEFLAG, ISAUDITE, CONSOLEMODULE, CUSTOMENCODING, ISFILEDSCONTROL)
VALUES (34, 4, '��¼��־����', 'security/loginLogAnalysisAction.do', '1/4/110054', '�������/ϵͳ����/��¼��־����', 'icon-048?#97CC52', NULL, NULL, NULL, '1', '1', '1', NULL, 4, '01', 3, '0', '1', NULL, 'sysmg', '0', NULL, '0', '0', NULL, '1');
INSERT INTO TAMENU (MENUID, PMENUID, MENUNAME, URL, MENUIDPATH, MENUNAMEPATH, ICONSKIN, SELECTIMAGE, REPORTID, ACCESSTIMEEL, EFFECTIVE, SECURITYPOLICY, ISDISMULTIPOS, QUICKCODE, SORTNO, RESOURCETYPE, MENULEVEL, ISLEAF, MENUTYPE, ISCACHE, SYSPATH, USEYAB003, TYPEFLAG, ISAUDITE, CONSOLEMODULE, CUSTOMENCODING, ISFILEDSCONTROL)
VALUES (35, 4, 'Java��ʱ����', 'scheduler/schedulerMgAction.do', '1/2/213169', '�������/ϵͳ����/Java��ʱ����', 'icon-051?#4D69B5', NULL, NULL, NULL, '1', '1', '1', NULL, 5, '01', 3, '0', '1', NULL, 'sysmg', '1', NULL, '0', '0', NULL, '1');
INSERT INTO TAMENU (MENUID, PMENUID, MENUNAME, URL, MENUIDPATH, MENUNAMEPATH, ICONSKIN, SELECTIMAGE, REPORTID, ACCESSTIMEEL, EFFECTIVE, SECURITYPOLICY, ISDISMULTIPOS, QUICKCODE, SORTNO, RESOURCETYPE, MENULEVEL, ISLEAF, MENUTYPE, ISCACHE, SYSPATH, USEYAB003, TYPEFLAG, ISAUDITE, CONSOLEMODULE, CUSTOMENCODING, ISFILEDSCONTROL)
VALUES (36, 4, '���ù���', 'sysapp/config/config.do', '1/173013/273014', '�������/��������/���ù���', 'icon-009?#AFD67C', NULL, NULL, NULL, '1', '1', '1', NULL, 0, '01', 3, '0', '1', NULL, 'sysmg', '1', NULL, '0', '1', NULL, '1');
INSERT INTO TAMENU (MENUID, PMENUID, MENUNAME, URL, MENUIDPATH, MENUNAMEPATH, ICONSKIN, SELECTIMAGE, REPORTID, ACCESSTIMEEL, EFFECTIVE, SECURITYPOLICY, ISDISMULTIPOS, QUICKCODE, SORTNO, RESOURCETYPE, MENULEVEL, ISLEAF, MENUTYPE, ISCACHE, SYSPATH, USEYAB003, TYPEFLAG, ISAUDITE, CONSOLEMODULE, CUSTOMENCODING, ISFILEDSCONTROL)
VALUES (38, 3, '�������', 'cache/cacheMgAction.do', '1/3/38', '�������/��������/�������', 'icon-032?#E1785A', NULL, NULL, NULL, '1', '1', '1', NULL, 2, '01', 3, '1', '1', NULL, 'sysmg', '1', NULL, '0', '0', NULL, '1');
INSERT INTO TAMENU (MENUID, PMENUID, MENUNAME, URL, MENUIDPATH, MENUNAMEPATH, ICONSKIN, SELECTIMAGE, REPORTID, ACCESSTIMEEL, EFFECTIVE, SECURITYPOLICY, ISDISMULTIPOS, QUICKCODE, SORTNO, RESOURCETYPE, MENULEVEL, ISLEAF, MENUTYPE, ISCACHE, SYSPATH, USEYAB003, TYPEFLAG, ISAUDITE, CONSOLEMODULE, CUSTOMENCODING, ISFILEDSCONTROL)
VALUES (100, 29, '�ҵ�֪ͨ', 'message/messageSearch.do', '1/29/100', '�������/֪ͨ����/�ҵ�֪ͨ', 'icon-052?#86a9eb', NULL, NULL, NULL, '1', '1', '1', NULL, 2, '01', 3, '1', '2', NULL, 'sysmg', '1', NULL, '0', '0', NULL, '1');
INSERT INTO TAMENU (MENUID, PMENUID, MENUNAME, URL, MENUIDPATH, MENUNAMEPATH, ICONSKIN, SELECTIMAGE, REPORTID, ACCESSTIMEEL, EFFECTIVE, SECURITYPOLICY, ISDISMULTIPOS, QUICKCODE, SORTNO, RESOURCETYPE, MENULEVEL, ISLEAF, MENUTYPE, ISCACHE, SYSPATH, USEYAB003, TYPEFLAG, ISAUDITE, CONSOLEMODULE, CUSTOMENCODING, ISFILEDSCONTROL)
VALUES (101, 4, '����ϵͳ����', 'sysapp/accessSystemAction.do', '1/4/101', '�������/ϵͳ����/����ϵͳ����', 'icon-024?#94C1F1', NULL, NULL, NULL, '0', '1', '1', NULL, 4, '01', 3, '0', '1', NULL, 'sysmg', '1', NULL, '0', '0', NULL, '1');
INSERT INTO TAMENU (MENUID, PMENUID, MENUNAME, URL, MENUIDPATH, MENUNAMEPATH, ICONSKIN, SELECTIMAGE, REPORTID, ACCESSTIMEEL, EFFECTIVE, SECURITYPOLICY, ISDISMULTIPOS, QUICKCODE, SORTNO, RESOURCETYPE, MENULEVEL, ISLEAF, MENUTYPE, ISCACHE, SYSPATH, USEYAB003, TYPEFLAG, ISAUDITE, CONSOLEMODULE, CUSTOMENCODING, ISFILEDSCONTROL)
VALUES (280, 2, '��������Ա����', 'org/developer/developerMg.do', '1/2/280', '�������/Ȩ�޹���/��������Ա����', 'icon-022?#e82774', NULL, NULL, NULL, '1', '1', '1', NULL, 6, '01', 3, '1', '1', NULL, 'sysmg', '1', NULL, '0', '0', NULL, '1');
INSERT INTO TAMENU (MENUID, PMENUID, MENUNAME, URL, MENUIDPATH, MENUNAMEPATH, ICONSKIN, SELECTIMAGE, REPORTID, ACCESSTIMEEL, EFFECTIVE, SECURITYPOLICY, ISDISMULTIPOS, QUICKCODE, SORTNO, RESOURCETYPE, MENULEVEL, ISLEAF, MENUTYPE, ISCACHE, SYSPATH, USEYAB003, TYPEFLAG, ISAUDITE, CONSOLEMODULE)
VALUES (290,4,'��־�������','logLevel/logLevelController.do','1/4/232732','�������/ϵͳ����/��־�������','icon-036?#00fafa','','','','1','1','1','',9,'01',3,'1','1','','sysmg','0',NULL,'0','0');
INSERT INTO TAMENU (MENUID, PMENUID, MENUNAME, URL, MENUIDPATH, MENUNAMEPATH, ICONSKIN, SELECTIMAGE, REPORTID, ACCESSTIMEEL, EFFECTIVE, SECURITYPOLICY, ISDISMULTIPOS, QUICKCODE, SORTNO, RESOURCETYPE, MENULEVEL, ISLEAF, MENUTYPE, ISCACHE, SYSPATH, USEYAB003, TYPEFLAG, ISAUDITE, CONSOLEMODULE, CUSTOMENCODING, ISFILEDSCONTROL)
VALUES (292, 4, 'sql热修改', 'modifySqlStatement/modifySqlStatementController.do', '1/4/292', '银海软件/系统管理/sql热修改', 'icon-011?#09dceb', NULL, NULL, '', '1', '1', '1', NULL, 8, '01', 3, '1', '1', NULL, 'sysmg', '1', NULL, '0', '0', '', '1');


INSERT INTO TAORG (ORGID,PORGID,ORGNAME,COSTOMNO,ORGIDPATH,ORGNAMEPATH,COSTOMNOPATH,ORGTYPE,SORT,YAB003,DIMENSION,CREATEUSER,CREATETIME,EFFECTIVE,ORGLEVEL,ISLEAF,TYPEFLAG,YAB139) VALUES (1,1,'�������','1','1','�������','0','01',0,'9999',NULL,0,sysdate,'1',0,'1',0,'9999');

INSERT INTO TAUSER (USERID,NAME,SEX,LOGINID,PASSWORD,PASSWORDFAULTNUM,PWDLASTMODIFYDATE,ISLOCK,SORT,EFFECTIVE,TEL,CREATEUSER,CREATETIME,DIRECTORGID,TYPEFLAG,AUTHMODE) VALUES (1,'��������Ա','1','developer','29PYtt0CYAXxrlJgzd/HUg==',0,sysdate,'0',0,'1','0',1,sysdate,1,0,'01');

INSERT INTO TAPOSITION (POSITIONID,ORGID,POSITIONNAME,POSITIONTYPE,CREATEPOSITIONID,ORGIDPATH,ORGNAMEPATH,VALIDTIME,CREATEUSER,CREATETIME,EFFECTIVE,ISADMIN,TYPEFLAG,ISDEVELOPER) VALUES (1,1,'��������Ա','2',1,'1','�������',NULL,1,sysdate,'1','1',0,1);

INSERT INTO TAUSERPOSITION (USERID,POSITIONID,MAINPOSITION,CREATEUSER,CREATETIME) VALUES (1,1,'1',1,sysdate);

insert into TALOCALCACHEVERSION(VERSION, CODETYPE) values (1,'');

INSERT INTO TAYAB003LEVELMG (PYAB003, YAB003) VALUES ('0', '9999');