--4.0.0-SNAPSHOT 升级 码表0/1标志位调整 2017-2-15
update AA10 set AAE120 = '2' where AAE120 = '0';
update AA10 set AAE120 = '0' where AAE120 = '1';
update AA10 set AAE120 = '1' where AAE120 = '2';
commit;
--4.0.0-SNAPSHOT 升级 调整yab003/yab139长度 2017-04-25
alter table taorg modify  YAB003 varchar(20);
alter table taorg modify  YAB139 varchar(20);

alter table aa10 modify  AAA102 varchar(20);
alter table aa10 modify  YAB003 varchar(20);

alter table TAYAB003LEVELMG modify  PYAB003 varchar(20);
alter table TAYAB003LEVELMG modify  YAB003 varchar(20);

alter table TAYAB139MG modify  YAB139 varchar(20);
alter table TAYAB139MG modify  YAB003 varchar(20);

alter table taadminyab139scope modify  YAB139 varchar(20);
--4.0.1-SNAPSHOT版本需要执行的sql 2017年9月1日10:33:51
ALTER TABLE taposition ADD  isdeveloper varchar2(1);
UPDATE TABLE taposition set isdeveloper = '1' where positionid=1;
INSERT INTO TAMENU (MENUID, PMENUID, MENUNAME, URL, MENUIDPATH, MENUNAMEPATH, ICONSKIN, SELECTIMAGE, REPORTID, ACCESSTIMEEL, EFFECTIVE, SECURITYPOLICY, ISDISMULTIPOS, QUICKCODE, SORTNO, RESOURCETYPE, MENULEVEL, ISLEAF, MENUTYPE, ISCACHE, SYSPATH, USEYAB003, TYPEFLAG, ISAUDITE, CONSOLEMODULE)
VALUES (280, 2, '超级管理员配置', 'org/developer/developerMg.do', '1/2/280', '银海软件/权限管理/字段授权', 'tree-folder-new', '', '', '', '1', '1', '1', '', 6, '01', 3, '1', '1', '', 'sysmg', '1', null, '0', '0');
COMMIT ;

--2017年9月18日17:34:30 权限认证新增码表
insert into aa10 (AAA100, AAA101, AAA102, AAA103, YAB003, AAE120, VER)
values ('AUTHMODE', '认证方式类型', '04', 'Key盘', '9999', '0', 0);

insert into aa10 (AAA100, AAA101, AAA102, AAA103, YAB003, AAE120, VER)
values ('AUTHMODE', '权限认证方式', '03', '人脸识别', '9999', '0', 0);

insert into aa10 (AAA100, AAA101, AAA102, AAA103, YAB003, AAE120, VER)
values ('AUTHMODE', '权限认证方式', '02', '指纹识别', '9999', '0', 0);

insert into aa10 (AAA100, AAA101, AAA102, AAA103, YAB003, AAE120, VER)
values ('AUTHMODE', '权限认证方式', '01', '用户名密码', '9999', '0', 0);
COMMIT ;

ALTER TABLE tauser ADD  authmode varchar2(2);
-- 4.1.0-RELEASE版本需要执行的sql 2017年11月21日
-- 日记输出级别 新增码表数据
insert into AA10 (AAA100, AAA101, AAA102, AAA103, YAB003, AAE120, VER)
values ('LOGLEVEL', '日志等级', '0', 'OFF', '9999', '0', 0);
insert into AA10 (AAA100, AAA101, AAA102, AAA103, YAB003, AAE120, VER)
values ('LOGLEVEL', '日志等级', '1', 'FATAL', '9999', '0', 0);
insert into AA10 (AAA100, AAA101, AAA102, AAA103, YAB003, AAE120, VER)
values ('LOGLEVEL', '日志等级', '2', 'ERROR', '9999', '0', 0);
insert into AA10 (AAA100, AAA101, AAA102, AAA103, YAB003, AAE120, VER)
values ('LOGLEVEL', '日志等级', '3', 'WARN', '9999', '0', 0);
insert into AA10 (AAA100, AAA101, AAA102, AAA103, YAB003, AAE120, VER)
values ('LOGLEVEL', '日志等级', '4', 'INFO', '9999', '0', 0);
insert into AA10 (AAA100, AAA101, AAA102, AAA103, YAB003, AAE120, VER)
values ('LOGLEVEL', '日志等级', '5', 'DEBUG', '9999', '0', 0);
insert into AA10 (AAA100, AAA101, AAA102, AAA103, YAB003, AAE120, VER)
values ('LOGLEVEL', '日志等级', '6', 'TRACE', '9999', '0', 0);
insert into AA10 (AAA100, AAA101, AAA102, AAA103, YAB003, AAE120, VER)
values ('LOGLEVEL', '日志等级', '7', 'ALL', '9999', '0', 0);
-- 4.1.0-RELEASE版本需要执行的sql 2017年11月21日
-- 日记输出级别 添加菜单数据
Insert into TAMENU (MENUID, PMENUID, MENUNAME, URL, MENUIDPATH, MENUNAMEPATH, ICONSKIN, SELECTIMAGE, REPORTID, ACCESSTIMEEL, EFFECTIVE, SECURITYPOLICY, ISDISMULTIPOS, QUICKCODE, SORTNO, RESOURCETYPE, MENULEVEL, ISLEAF, MENUTYPE, ISCACHE, SYSPATH, USEYAB003, TYPEFLAG, ISAUDITE, CONSOLEMODULE)
values (290,4,'日志输出级别','logLevel/logLevelController.do','1/4/232732','银海软件/系统管理/日志输出级别','icon-036?#00fafa',null,null,null,'1','1','1',null,9,'01',3,'1','1',null,'sysmg','0',null,'0','0');
--菜单图标更新
UPDATE TAMENU SET ICONSKIN = 'icon-073?#3413ed' WHERE MENUID = '1';
UPDATE TAMENU SET ICONSKIN = 'icon-004?#87bfe8' WHERE MENUID = '2';
UPDATE TAMENU SET ICONSKIN = 'icon-001?#6A6A6A' WHERE MENUID = '3';
UPDATE TAMENU SET ICONSKIN = 'icon-005?#E1785A' WHERE MENUID = '4';
UPDATE TAMENU SET ICONSKIN = 'icon-010?#E7B346' WHERE MENUID = '5';
UPDATE TAMENU SET ICONSKIN = 'icon-029?#88BBF1' WHERE MENUID = '6';
UPDATE TAMENU SET ICONSKIN = 'icon-011?#33475F' WHERE MENUID = '7';
UPDATE TAMENU SET ICONSKIN = 'icon-023?#B59BC9' WHERE MENUID = '8';
UPDATE TAMENU SET ICONSKIN = 'icon-014?#936BB2' WHERE MENUID = '9';
UPDATE TAMENU SET ICONSKIN = 'icon-057?#56ABE4' WHERE MENUID = '10';
UPDATE TAMENU SET ICONSKIN = 'icon-065?#E5937C' WHERE MENUID = '11';
UPDATE TAMENU SET ICONSKIN = 'icon-026?#B4D984' WHERE MENUID = '12';
UPDATE TAMENU SET ICONSKIN = 'icon-049?#56ABE4' WHERE MENUID = '13';
UPDATE TAMENU SET ICONSKIN = 'icon-035?#97CC52' WHERE MENUID = '14';
UPDATE TAMENU SET ICONSKIN = 'icon-060?#00BB9C' WHERE MENUID = '15';
UPDATE TAMENU SET ICONSKIN = 'icon-053?#deaf49' WHERE MENUID = '16';
UPDATE TAMENU SET ICONSKIN = 'icon-028?#B196C7' WHERE MENUID = '17';
UPDATE TAMENU SET ICONSKIN = 'icon-067?#E1785A' WHERE MENUID = '18';
UPDATE TAMENU SET ICONSKIN = 'icon-065?#deaf49' WHERE MENUID = '19';
UPDATE TAMENU SET ICONSKIN = 'icon-037?#deaf49' WHERE MENUID = '20';
UPDATE TAMENU SET ICONSKIN = 'icon-006?#E1785A' WHERE MENUID = '21';
UPDATE TAMENU SET ICONSKIN = 'icon-005?#E1785A' WHERE MENUID = '22';
UPDATE TAMENU SET ICONSKIN = 'icon-015?#97CC52' WHERE MENUID = '23';
UPDATE TAMENU SET ICONSKIN = 'icon-045?#33475F' WHERE MENUID = '24';
UPDATE TAMENU SET ICONSKIN = 'icon-048?#42dbd4' WHERE MENUID = '25';
UPDATE TAMENU SET ICONSKIN = 'icon-008?#a397e8' WHERE MENUID = '26';
UPDATE TAMENU SET ICONSKIN = 'icon-001?#6A6A6A' WHERE MENUID = '27';
UPDATE TAMENU SET ICONSKIN = 'icon-027?#00BB9C' WHERE MENUID = '28';
UPDATE TAMENU SET ICONSKIN = 'icon-017?#cf829d' WHERE MENUID = '29';
UPDATE TAMENU SET ICONSKIN = 'icon-071?#e37de3' WHERE MENUID = '30';
UPDATE TAMENU SET ICONSKIN = 'icon-050?#27d971' WHERE MENUID = '31';
UPDATE TAMENU SET ICONSKIN = 'icon-039?#db4b89' WHERE MENUID = '32';
UPDATE TAMENU SET ICONSKIN = 'icon-037?#8ABCF1' WHERE MENUID = '33';
UPDATE TAMENU SET ICONSKIN = 'icon-048?#97CC52' WHERE MENUID = '34';
UPDATE TAMENU SET ICONSKIN = 'icon-051?#4D69B5' WHERE MENUID = '35';
UPDATE TAMENU SET ICONSKIN = 'icon-009?#AFD67C' WHERE MENUID = '36';
UPDATE TAMENU SET ICONSKIN = 'icon-032?#E1785A' WHERE MENUID = '38';
UPDATE TAMENU SET ICONSKIN = 'icon-052?#86a9eb' WHERE MENUID = '100';
UPDATE TAMENU SET ICONSKIN = 'icon-024?#94C1F1' WHERE MENUID = '101';
UPDATE TAMENU SET ICONSKIN = 'icon-022?#e82774' WHERE MENUID = '280';
--4.1.0-RELEASE版本需要执行的sql 2018年3月21日
--集群server配置表变更
--删除原来SERVERADDRESS表
DROP TABLE IF EXISTS SERVERADDRESS;
--创建新的集群配置表
CREATE TABLE CLUSTERCONFIG(
  CLUSTERID INT(10) NOT NULL COMMENT '集群配置id',
  CLUSTERNAME VARCHAR(200) COMMENT '集群名称',
  CLUSTERAPP VARCHAR(200) COMMENT '应用名称',
  CLUSTERURL VARCHAR(200) NOT NULL COMMENT '服务URL',
  CLUSTERDESC VARCHAR(200) COMMENT '描述',
  PRIMARY KEY (CLUSTERID)
);
ALTER TABLE CLUSTERCONFIG COMMENT '集群配置表';
--新增集群配置功能菜单
INSERT INTO TAMENU (MENUID, PMENUID, MENUNAME, URL, MENUIDPATH, MENUNAMEPATH, ICONSKIN, SELECTIMAGE, REPORTID, ACCESSTIMEEL, EFFECTIVE, SECURITYPOLICY, ISDISMULTIPOS, QUICKCODE, SORTNO, RESOURCETYPE, MENULEVEL, ISLEAF, MENUTYPE, ISCACHE, SYSPATH, USEYAB003, TYPEFLAG, ISAUDITE, CONSOLEMODULE, CUSTOMENCODING, ISFILEDSCONTROL)
VALUES (37, 4, '集群server配置管理', 'clusterConfig/clusterConfigController.do', '1/4/37', '银海软件/开发管理/集群server配置管理', 'icon-049?#56ABE4', NULL, NULL, NULL, '1', '1', '1', NULL, 10, '01', 3, '1', '1', NULL, 'sysmg', '1', NULL, '0', '0', NULL, '1');
COMMIT;

/*Add By MinusZero In 2018/08/20 Start***/
INSERT INTO TAMENU (MENUID, PMENUID, MENUNAME, URL, MENUIDPATH, MENUNAMEPATH, ICONSKIN, SELECTIMAGE, REPORTID, ACCESSTIMEEL, EFFECTIVE, SECURITYPOLICY, ISDISMULTIPOS, QUICKCODE, SORTNO, RESOURCETYPE, MENULEVEL, ISLEAF, MENUTYPE, ISCACHE, SYSPATH, USEYAB003, TYPEFLAG, ISAUDITE, CONSOLEMODULE, CUSTOMENCODING, ISFILEDSCONTROL)
VALUES (291, 2, '组织正副职管理', 'org/positionMgAction.do', '1/2/291', '银海软件/权限管理/组织正副职管理', 'icon-011?#09dceb', NULL, NULL, '', '1', '1', '1', NULL, 8, '01', 3, '1', '1', NULL, 'sysmg', '1', NULL, '0', '0', '', '1');
COMMIT;

UPDATE TAMENU SET `SECURITYPOLICY`='2' WHERE (MENUID=21);
UPDATE TAMENU SET `SECURITYPOLICY`='2' WHERE (MENUID=22);
UPDATE TAMENU SET `SECURITYPOLICY`='2' WHERE (MENUID=23);
UPDATE TAMENU SET `SECURITYPOLICY`='2' WHERE (MENUID=24);
UPDATE TAMENU SET `SECURITYPOLICY`='2' WHERE (MENUID=25);
UPDATE TAMENU SET `SECURITYPOLICY`='2' WHERE (MENUID=26);
COMMIT;

DROP TABLE IF EXISTS TAZKADDRESSMG;
create table TAZKADDRESSMG
(
  zkid             VARCHAR(20) not null COMMENT '消息id',
  zkaddress        VARCHAR(200) COMMENT '通知附件',
  appname          VARCHAR(60) COMMENT '附件名称',
  appnamespace     VARCHAR(30) COMMENT '附件名称'
);
DROP TABLE IF EXISTS JOB_BUSY_FREE_MG;
create table JOB_BUSY_FREE_MG
(
  jobstatus             VARCHAR(2)  COMMENT '任务状态',
  zkid                  VARCHAR(20) not null COMMENT '注册中心zkid',
  cron                  VARCHAR(20)  COMMENT '闲忙时间点',
  jobtype               VARCHAR(2)  COMMENT '任务类型',
  jobname               VARCHAR(20) COMMENT '任务名称',
  ips                   VARCHAR(20)  COMMENT 'ip地址',
  ebfid                 VARCHAR(20) not null COMMENT '闲忙任务id',
  CONSTRAINT JOB_BUSY_FREE_MG_PK PRIMARY KEY (ebfid)
);
INSERT INTO TAMENU (MENUID, PMENUID, MENUNAME, URL, MENUIDPATH, MENUNAMEPATH, ICONSKIN, SELECTIMAGE, REPORTID, ACCESSTIMEEL, EFFECTIVE, SECURITYPOLICY, ISDISMULTIPOS, QUICKCODE, SORTNO, RESOURCETYPE, MENULEVEL, ISLEAF, MENUTYPE, ISCACHE, SYSPATH, USEYAB003, TYPEFLAG, ISAUDITE, CONSOLEMODULE, CUSTOMENCODING, ISFILEDSCONTROL)
VALUES (292, 4, 'sql热修改', 'modifySqlStatement/modifySqlStatementController.do', '1/4/292', '银海软件/系统管理/sql热修改', 'icon-011?#09dceb', NULL, NULL, '', '1', '1', '1', NULL, 8, '01', 3, '1', '1', NULL, 'sysmg', '1', NULL, '0', '0', '', '1');
INSERT INTO TAMENU (MENUID, PMENUID, MENUNAME, URL, MENUIDPATH, MENUNAMEPATH, ICONSKIN, SELECTIMAGE, REPORTID, ACCESSTIMEEL, EFFECTIVE, SECURITYPOLICY, ISDISMULTIPOS, QUICKCODE, SORTNO, RESOURCETYPE, MENULEVEL, ISLEAF, MENUTYPE, ISCACHE, SYSPATH, USEYAB003, TYPEFLAG, ISAUDITE, CONSOLEMODULE, CUSTOMENCODING, ISFILEDSCONTROL)
VALUES (293, 3, 'elasticJob管理', null, '1/3/293', '银海软件/开发管理/elasticJob管理', 'icon-001?#cfaf11', null, null, null, '1', '1', '1', null, 7, '01', 3, '0', '1', null, 'sysmg', '0', null, '0', '0', null, '0');
INSERT INTO TAMENU (MENUID, PMENUID, MENUNAME, URL, MENUIDPATH, MENUNAMEPATH, ICONSKIN, SELECTIMAGE, REPORTID, ACCESSTIMEEL, EFFECTIVE, SECURITYPOLICY, ISDISMULTIPOS, QUICKCODE, SORTNO, RESOURCETYPE, MENULEVEL, ISLEAF, MENUTYPE, ISCACHE, SYSPATH, USEYAB003, TYPEFLAG, ISAUDITE, CONSOLEMODULE, CUSTOMENCODING, ISFILEDSCONTROL)
VALUES (294, 293, 'zk管理', 'elasticJob/zookeeperCenterManagerController.do', '1/3/293/294', '银海软件/开发管理/elasticJob管理/zk管理', 'icon-005?', null, null, null, '1', '1', '1', null, 1, '01', 4, '1', '1', null, 'sysmg', '0', null, '0', '0', null, '0');
INSERT INTO TAMENU (MENUID, PMENUID, MENUNAME, URL, MENUIDPATH, MENUNAMEPATH, ICONSKIN, SELECTIMAGE, REPORTID, ACCESSTIMEEL, EFFECTIVE, SECURITYPOLICY, ISDISMULTIPOS, QUICKCODE, SORTNO, RESOURCETYPE, MENULEVEL, ISLEAF, MENUTYPE, ISCACHE, SYSPATH, USEYAB003, TYPEFLAG, ISAUDITE, CONSOLEMODULE, CUSTOMENCODING, ISFILEDSCONTROL)
VALUES (295, 293, '闲忙job管理', 'elasticJob/freeBusyHourManagerController.do', '1/3/293/295', '银海软件/开发管理/elasticJob管理/闲忙job管理', 'icon-060?', null, null, null, '1', '1', '1', null, 2, '01', 4, '1', '1', null, 'sysmg', '0', null, '0', '0', null, '0');
INSERT INTO TAMENU (MENUID, PMENUID, MENUNAME, URL, MENUIDPATH, MENUNAMEPATH, ICONSKIN, SELECTIMAGE, REPORTID, ACCESSTIMEEL, EFFECTIVE, SECURITYPOLICY, ISDISMULTIPOS, QUICKCODE, SORTNO, RESOURCETYPE, MENULEVEL, ISLEAF, MENUTYPE, ISCACHE, SYSPATH, USEYAB003, TYPEFLAG, ISAUDITE, CONSOLEMODULE, CUSTOMENCODING, ISFILEDSCONTROL)
VALUES (296, 293, 'job管理', 'elasticJob/elasticJobManagerConsoleController.do', '1/3/293/296', '银海软件/开发管理/elasticJob管理/job管理', 'icon-008?', null, null, null, '1', '1', '1', null, 0, '01', 4, '1', '1', null, 'sysmg', '0', null, '0', '0', null, '0');
COMMIT;

/*********End In 2018/08/16*****/