kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ${meta_name}
subjects:
  - kind: ServiceAccount
    name: ${meta_name}
    namespace: ${namespace}
roleRef:
  kind: ClusterRole
  name: nfs-client-provisioner-runner
  apiGroup: rbac.authorization.k8s.io
