apiVersion: v1
kind: Service
metadata:
  name: zk-name-hs
  namespace: name-space
  labels:
    app: zk-name
spec:
  ports:
  - port: 2888
    name: server
  - port: 3888
    name: leader-election
  clusterIP: None
  selector:
    app: zk-name
---
apiVersion: v1
kind: Service
metadata:
  name: zk-name-cs
  namespace: name-space
  labels:
    app: zk-name
spec:
  type: NodePort
  ports:
  - port: 2181
    name: client
    nodePort: node-Port
  selector:
    app: zk-name
---
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: zk-name-pdb
  namespace: name-space
spec:
  selector:
    matchLabels:
      app: zk-name
  maxUnavailable: 1
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: zk-name
  namespace: name-space
spec:
  selector:
    matchLabels:
      app: zk-name
  serviceName: zk-name-hs
  replicas: 3
  updateStrategy:
    type: RollingUpdate
  podManagementPolicy: Parallel
  template:
    metadata:
      labels:
        app: zk-name
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: "app"
                    operator: In
                    values:
                    - zk-name
              topologyKey: "kubernetes.io/hostname"
      containers:
      - name: kubernetes-zookeeper
        imagePullPolicy: Always
        image: zk-image-url
        resources:
          requests:
            memory: "0.8Gi"
            cpu: "0.2"
        ports:
        - containerPort: 2181
          name: client
        - containerPort: 2888
          name: server
        - containerPort: 3888
          name: leader-election
        command:
        - sh
        - -c
        - "start-zookeeper \
          --servers=3 \
          --data_dir=/var/lib/zookeeper/data \
          --data_log_dir=/var/lib/zookeeper/data/log \
          --conf_dir=/opt/zookeeper/conf \
          --client_port=2181 \
          --election_port=3888 \
          --server_port=2888 \
          --tick_time=2000 \
          --init_limit=10 \
          --sync_limit=5 \
          --heap=512M \
          --max_client_cnxns=60 \
          --snap_retain_count=3 \
          --purge_interval=12 \
          --max_session_timeout=40000 \
          --min_session_timeout=4000 \
          --log_level=INFO"
        readinessProbe:
          exec:
            command:
            - sh
            - -c
            - "zookeeper-ready 2181"
          initialDelaySeconds: 10
          timeoutSeconds: 5
        livenessProbe:
          exec:
            command:
            - sh
            - -c
            - "zookeeper-ready 2181"
          initialDelaySeconds: 10
          timeoutSeconds: 5
        volumeMounts:
        - name: storagename
          mountPath: /var/lib/zookeeper
  volumeClaimTemplates:
  - metadata:
      name: storagename
    spec:
      storageClassName: storagename
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 2Gi